import { ItineraryPlan } from "../types";

export const SAMPLE_VACATION_PLAN: ItineraryPlan = {
  id: "sample-vacation-kyoto",
  mode: "vacation",
  title: "4-Day Kyoto & Arashiyama Cultural Reverie",
  destinationOrTown: "Kyoto, Japan",
  summary: "A carefully balanced 4-day journey blending serene bamboo paths, historic wooden shrines, artisan matcha tearooms, and lantern-lit alley dining.",
  highlights: [
    "Dawn walk through the quiet Arashiyama Bamboo Grove before crowds arrive",
    "Hidden moss gardens at Gio-ji Temple and historic Sagano preserves",
    "Evening kaiseki dining and secret cocktail bar in Pontocho Alley",
    "Private tea ceremony demonstration with Uji master blend",
  ],
  totalDays: 4,
  createdAt: new Date().toISOString(),
  tags: ["Gastronomy & Local Food", "Scenic & Outdoors", "History & Architecture", "Hidden Gems / Non-Touristy"],
  weatherSummary: "Mild autumn breeze, 21°C / 70°F with clear skies.",
  mapCenter: { lat: 35.0116, lng: 135.7681 },
  mapZoom: 13,
  customPace: "balanced",
  budgetTier: "mid-range",
  days: [
    {
      dayNumber: 1,
      dayTitle: "Day 1: Western Foothills & Whispering Bamboo",
      theme: "Arashiyama Groves & Historic Sanctuaries",
      summary: "Start in the peaceful western mountains of Kyoto, admiring historic wooden architecture and secluded moss gardens.",
      estimatedTotalBudget: "$65 - $110",
      activities: [
        {
          id: "kyoto-1-1",
          time: "07:45 AM - 09:30 AM",
          name: "Arashiyama Bamboo Grove & Tenryu-ji Garden",
          category: "nature",
          description: "Soaring green stalks of bamboo that rustle in the morning wind, leading directly into the UNESCO-listed 14th-century Zen temple gardens.",
          insiderTip: "Arriving before 8:00 AM gives you the entire path in total morning serenity and golden light.",
          approxCost: "¥500 (~$3.50)",
          rating: 4.9,
          coordinates: { lat: 35.0169, lng: 135.6713 },
          address: "Sagatenryuji Susukinobabacho, Ukyo Ward, Kyoto",
          durationMinutes: 90,
        },
        {
          id: "kyoto-1-2",
          time: "10:00 AM - 11:30 AM",
          name: "Gio-ji Secluded Moss Temple",
          category: "hidden-gem",
          description: "A tranquil thatched-roof hermitage nestled within a lush emerald carpet of over 40 species of moss.",
          insiderTip: "Look for the round Yoshino window in the main hall framing the vivid maple trees.",
          approxCost: "¥300 (~$2)",
          rating: 4.8,
          coordinates: { lat: 35.0253, lng: 135.6669 },
          address: "32 Sagatoriimoto Kozakacho, Ukyo Ward, Kyoto",
          durationMinutes: 60,
        },
        {
          id: "kyoto-1-3",
          time: "12:30 PM - 02:00 PM",
          name: "Saga Tofu Ine Artisanal Yuba Luncheon",
          category: "food",
          description: "Freshly made hot soy milk skin (yuba) and silken tofu served alongside seasonal pickled mountain vegetables overlooking the Oi River.",
          insiderTip: "Reserve a second-floor window table for panoramic views of Togetsukyo Bridge.",
          approxCost: "¥2,200 (~$15)",
          rating: 4.7,
          coordinates: { lat: 35.0142, lng: 135.6775 },
          address: "19 Sagatenryuji Tsukurimichicho, Ukyo Ward, Kyoto",
          durationMinutes: 75,
        },
        {
          id: "kyoto-1-4",
          time: "03:00 PM - 05:00 PM",
          name: "Okochi Sanso Villa & Hilltop Matcha Pavilion",
          category: "culture",
          description: "The private mountain estate of silent-film legend Denjiro Okochi, featuring panoramic vistas of Kyoto Valley.",
          insiderTip: "Your entry ticket includes a complimentary cup of stone-ground matcha and seasonal sweet at the tea pavilion.",
          approxCost: "¥1,000 (~$7)",
          rating: 4.9,
          coordinates: { lat: 35.0179, lng: 135.6685 },
          address: "8 Sagaogurayama Tabuchiyamacho, Ukyo Ward, Kyoto",
          durationMinutes: 90,
        },
        {
          id: "kyoto-1-5",
          time: "07:00 PM - 09:00 PM",
          name: "Pontocho Alley Izakaya & Craft Sake Tasting",
          category: "nightlife",
          description: "Atmospheric narrow pedestrian alley lined with traditional timber machiya townhouses illuminated by red lanterns.",
          insiderTip: "Duck into the second-floor sake bars tucked down the narrow side corridors for rare Kyoto microbrews.",
          approxCost: "$35 - $60",
          rating: 4.8,
          coordinates: { lat: 35.0062, lng: 135.7712 },
          address: "Pontocho-dori, Nakagyo Ward, Kyoto",
          durationMinutes: 120,
        },
      ],
    },
    {
      dayNumber: 2,
      dayTitle: "Day 2: Eastern Temples & Philosophers Path",
      theme: "Higashiyama Heritage & Handcrafted Pottery",
      summary: "Explore the gentle stone canal path, ancient wood-carved pavilions, and artisan craft shops in historic Gion.",
      estimatedTotalBudget: "$50 - $90",
      activities: [
        {
          id: "kyoto-2-1",
          time: "08:30 AM - 10:30 AM",
          name: "Ginkaku-ji (Silver Pavilion) & Sand Zen Garden",
          category: "culture",
          description: "Elegant zen temple with meticulously raked silver sand dunes and reflective pond reflecting surrounding pines.",
          insiderTip: "Walk the elevated hill trail behind the pavilion for a view over the sand sea toward the city.",
          approxCost: "¥500 (~$3.50)",
          rating: 4.8,
          coordinates: { lat: 35.0272, lng: 135.7982 },
          address: "2 Ginkakujicho, Sakyo Ward, Kyoto",
          durationMinutes: 90,
        },
        {
          id: "kyoto-2-2",
          time: "11:00 AM - 12:30 PM",
          name: "Philosopher's Walk & Hidden Bookstore Alley",
          category: "nature",
          description: "Picturesque stone path following a canal lined with cherry trees, charming indie coffee kiosks, and wild neighborhood cats.",
          insiderTip: "Stop at Omen restaurant halfway down for handmade thick udon noodles with sesame seasoning.",
          approxCost: "Free",
          rating: 4.7,
          coordinates: { lat: 35.0225, lng: 135.7944 },
          address: "Tetsugaku-no-Michi, Sakyo Ward, Kyoto",
          durationMinutes: 80,
        },
        {
          id: "kyoto-2-3",
          time: "01:00 PM - 02:30 PM",
          name: "Omen Kodai-ji Traditional Udon & Tempura",
          category: "food",
          description: "Famous local noodle institution crafting thick wheat noodles served with fresh local herbs, burdock, and seasonal pickles.",
          insiderTip: "Pour toasted sesame generously into your dipping broth for maximum umami.",
          approxCost: "¥1,800 (~$12)",
          rating: 4.8,
          coordinates: { lat: 35.0005, lng: 135.7818 },
          address: "358 Masuyacho, Higashiyama Ward, Kyoto",
          durationMinutes: 60,
        },
        {
          id: "kyoto-2-4",
          time: "03:30 PM - 05:30 PM",
          name: "Kiyomizu-dera Wooden Stage & Sunset View",
          category: "sightseeing",
          description: "Ancient hillside temple constructed entirely without a single nail, offering grand vistas of Kyoto against mountain sunsets.",
          insiderTip: "Drink from Otowa Waterfall below the main hall for health, longevity, or success in studies.",
          approxCost: "¥400 (~$3)",
          rating: 4.9,
          coordinates: { lat: 34.9949, lng: 135.7850 },
          address: "1-294 Kiyomizu, Higashiyama Ward, Kyoto",
          durationMinutes: 100,
        },
      ],
    },
    {
      dayNumber: 3,
      dayTitle: "Day 3: Thousand Vermilion Torii & Sake Cellars",
      theme: "Southern Mysticism & Fushimi Canals",
      summary: "Hike through the mountain tunnels of vermilion torii gates at Fushimi Inari and visit historic 400-year-old sake breweries.",
      estimatedTotalBudget: "$45 - $80",
      activities: [
        {
          id: "kyoto-3-1",
          time: "07:30 AM - 10:30 AM",
          name: "Fushimi Inari Upper Mountain Summit Pilgrimage",
          category: "culture",
          description: "Thousands of brilliant orange-red torii gates winding through sacred pine forests up Mount Inari.",
          insiderTip: "Continue past the Yotsutsuji crossroad for quiet mountain shrines where 90% of tourists turn back.",
          approxCost: "Free",
          rating: 5.0,
          coordinates: { lat: 34.9671, lng: 135.7727 },
          address: "68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto",
          durationMinutes: 150,
        },
        {
          id: "kyoto-3-2",
          time: "11:30 AM - 01:30 PM",
          name: "Gekkeikan Okura Sake Museum & Tasting Flights",
          category: "hidden-gem",
          description: "Historic 1637 brewery along weeping willow canals showcasing traditional wooden fermentation barrels and underground spring water.",
          insiderTip: "Fill up your water bottle with the pure Gokosui spring water flowing outside the brewery gate.",
          approxCost: "¥600 (~$4)",
          rating: 4.8,
          coordinates: { lat: 34.9309, lng: 135.7601 },
          address: "247 Minamihamacho, Fushimi Ward, Kyoto",
          durationMinutes: 90,
        },
        {
          id: "kyoto-3-3",
          time: "02:30 PM - 04:30 PM",
          name: "Tofuku-ji Hojo Stone Garden & Valley Bridge",
          category: "nature",
          description: "Famous for its sweeping wooden covered bridge overlooking a lush sea of Japanese maple trees and checkboard moss garden.",
          insiderTip: "The northern garden's moss and stone checkerboard design was created by legendary modernist designer Mirei Shigemori.",
          approxCost: "¥1,000 (~$7)",
          rating: 4.9,
          coordinates: { lat: 34.9811, lng: 135.7742 },
          address: "15-778 Honmachi, Higashiyama Ward, Kyoto",
          durationMinutes: 90,
        },
      ],
    },
    {
      dayNumber: 4,
      dayTitle: "Day 4: Historic Markets & Hidden Machiya Cafes",
      theme: "Culinary Alchemy & Modern Crafts",
      summary: "Immerse yourself in Kyoto's 400-year-old 'Kitchen' market, artisan ceramic workshops, and secluded courtyard coffee roasteries.",
      estimatedTotalBudget: "$55 - $95",
      activities: [
        {
          id: "kyoto-4-1",
          time: "09:00 AM - 11:30 AM",
          name: "Nishiki Market Pantry & Skewer Tastings",
          category: "food",
          description: "Five bustling city blocks packed with more than one hundred stalls selling baby octopus with quail eggs, dashi tamagoyaki, and sesame crackers.",
          insiderTip: "Eat food directly in front of the stall where purchased to follow local etiquette.",
          approxCost: "$15 - $25",
          rating: 4.7,
          coordinates: { lat: 35.0050, lng: 135.7649 },
          address: "Nakagyo Ward, Kyoto",
          durationMinutes: 120,
        },
        {
          id: "kyoto-4-2",
          time: "12:30 PM - 02:00 PM",
          name: "Weekenders Coffee Courtyard Sanctuary",
          category: "cafe",
          description: "A hidden specialty espresso bar tucked into the far corner of a traditional gravel parking lot behind a 100-year-old machiya house.",
          insiderTip: "Try their seasonal Ethiopian drip coffee while seated by the miniature moss bonsai garden.",
          approxCost: "$5 - $8",
          rating: 4.9,
          coordinates: { lat: 35.0094, lng: 135.7661 },
          address: "560 Honeyanocho, Nakagyo Ward, Kyoto",
          durationMinutes: 60,
        },
        {
          id: "kyoto-4-3",
          time: "03:00 PM - 05:00 PM",
          name: "Kamogawa River Delta Stone Stepping Stones",
          category: "relaxation",
          description: "Iconic stone turtle and bird stepping stones crossing the confluence of the Kamo and Takano rivers, beloved by local students and musicians.",
          insiderTip: "Pick up a pastry from nearby bakery Shinshindo and watch the heron birds fish in the river shallows.",
          approxCost: "Free",
          rating: 4.8,
          coordinates: { lat: 35.0305, lng: 135.7725 },
          address: "Shimogamo Miyakawacho, Sakyo Ward, Kyoto",
          durationMinutes: 90,
        },
      ],
    },
  ],
};

export const SAMPLE_HOMETOWN_PLAN: ItineraryPlan = {
  id: "sample-hometown-outing",
  mode: "hometown",
  title: "Local Explorer: Half-Day Hidden Gems & Riverside Outing",
  destinationOrTown: "Brooklyn / Hudson Waterfront, NY",
  summary: "A native insider outing curated for 3–5 hours within 15 km. Built for mild weather, avoiding tourist traps in favor of neighborhood artisan spots and skyline waterfront benches.",
  highlights: [
    "Single-origin espresso & cardamom pastries at an indie carriage-house roaster",
    "Tranquil gravel sculpture path and native wildflower meadow",
    "Hidden rooftop courtyard with panoramic estuary vistas",
  ],
  totalDays: 1,
  createdAt: new Date().toISOString(),
  tags: ["Half-Day", "15km Radius", "Solo Chill & Date", "Mild 22°C"],
  weatherSummary: "Sunny & clear, 22°C / 72°F with light southern breeze.",
  mapCenter: { lat: 40.7028, lng: -73.9928 },
  mapZoom: 14,
  days: [
    {
      dayNumber: 1,
      dayTitle: "Today's Local Outing: Artisanal Coffee & Waterfront Sanctuary",
      theme: "Quiet Corners & Neighborhood Flavors",
      summary: "3.5 hour curated loop away from crowded avenues.",
      estimatedTotalBudget: "$25 - $45",
      activities: [
        {
          id: "ht-1",
          time: "10:30 AM - 11:30 AM",
          name: "The Carriage House Roastery & Sourdough Corner",
          category: "cafe",
          description: "An unpretentious brick carriage-house micro-roastery serving small-batch cortados and warm cardamom sourdough rolls.",
          insiderTip: "Head to the back outdoor patio under the grape vines for the most peaceful reading nook.",
          approxCost: "$7 - $12",
          rating: 4.9,
          coordinates: { lat: 40.7032, lng: -73.9905 },
          address: "Historic Alleyway Quarter",
          durationMinutes: 60,
        },
        {
          id: "ht-2",
          time: "11:45 AM - 01:15 PM",
          name: "Estuary Salt Marsh & Wooden Boardwalk Lookout",
          category: "nature",
          description: "Restored tidal wetlands and hidden gravel pathways offering quiet skyline views, native marsh grasses, and peaceful bird-watching.",
          insiderTip: "The third pier bench facing northwest has an unobstructed view of the water with zero foot traffic.",
          approxCost: "Free",
          rating: 4.8,
          coordinates: { lat: 40.7015, lng: -73.9962 },
          address: "Waterfront Nature Pier 3",
          durationMinutes: 90,
        },
        {
          id: "ht-3",
          time: "01:30 PM - 02:30 PM",
          name: "Artisan Woodfire Pantry & Neighborhood Tapas",
          category: "food",
          description: "A cozy family-owned neighborhood counter offering hand-pulled mozzarella sandwiches, heirloom tomato salads, and house spritzes.",
          insiderTip: "Ask for the daily blackboard special with whipped ricotta and hot honey drizzle.",
          approxCost: "$16 - $28",
          rating: 4.9,
          coordinates: { lat: 40.7048, lng: -73.9918 },
          address: "Main Street Arcade",
          durationMinutes: 60,
        },
      ],
    },
  ],
};
