import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "es" | "eu";

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallbackOrParams?: string | Record<string, string | number>) => string;
  formatCurrency: (amount: number, currencySymbol?: string) => string;
}

const LANGUAGE_STORAGE_KEY = "localexplorer_lang_v1";

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Header
    "nav.brand": "LocalExplorer AI",
    "nav.subtitle": "Cultural Trip Planner & Hometown Guide",
    "nav.vacation": "Vacation Mode",
    "nav.hometown": "Hometown Mode",
    "nav.tasteProfile": "Taste Profile",
    "nav.mySpots": "My Places",
    "nav.history": "History",
    "nav.savedTrips": "Saved Trips",
    "nav.syncReady": "Synced",
    "nav.saving": "Saving...",
    "nav.offline": "Offline",
    "nav.cached": "Cached",

    // Actions & Tools
    "action.saveTrip": "Save Trip",
    "action.saved": "Saved",
    "action.share": "Share",
    "action.export": "Export",
    "action.print": "Print Daily Maps",
    "action.groupHub": "Group Hub",
    "action.pocketGuide": "Offline Pocket",
    "action.adjustSchedule": "Live Time Adjuster",
    "action.liveNavigator": "Live Navigator",
    "action.regenerate": "Regenerate All",
    "action.reiterate": "Fine-Tune Itinerary",
    "action.addActivity": "Add Activity",
    "action.allDays": "All Days",
    "action.day": "Day",
    "action.days": "Days",
    "action.close": "Close",
    "action.cancel": "Cancel",
    "action.save": "Save",
    "action.delete": "Delete",
    "action.edit": "Edit",
    "action.copyLink": "Copy Invite Link",
    "action.copyCode": "Copy Code",

    // Vacation Form
    "vacation.title": "Vacation Itinerary Planner",
    "vacation.subtitle": "Cost-aware, multi-day cultural itineraries with authentic hidden gems & verified route optimization",
    "vacation.tripMode": "Trip Mode:",
    "vacation.singleDest": "Single Destination",
    "vacation.multiDest": "Multi-Destination / Road Trip",
    "vacation.destinationLabel": "Destination City or Region (Advisor & Verifier)",
    "vacation.geocoding": "Precise Geocoding",
    "vacation.popular": "Popular:",
    "vacation.multiCityStops": "Multi-City Route Stops",
    "vacation.stop": "Stop",
    "vacation.addStop": "Add Another Stop / City",
    "vacation.groupSize": "Vacation Group Size",
    "vacation.groupSizeDesc": "Number of people traveling in your party",
    "vacation.person": "Person",
    "vacation.people": "People",
    "vacation.solo": "Solo Traveler",
    "vacation.couple": "Couple (2)",
    "vacation.smallGroup": "Small Group (4)",
    "vacation.largeGroup": "Large Group (6+)",
    "vacation.accommodationTitle": "Booked Accommodation & Stay Context",
    "vacation.accommodationSubtitle": "Specify hotels, check-in and check-out days & times for single or multi-destination stays",
    "vacation.accommodationHeading": "Booked Accommodations & Stay Context",
    "vacation.accommodationSub": "Define daily start/end locations, check-in and check-out days & times",
    "vacation.showAccommodation": "Show Accommodation Card",
    "vacation.hideAccommodation": "Hide Accommodation Card",
    "vacation.addStay": "Add Another Stay",
    "vacation.stay": "Stay",
    "vacation.accommodationName": "Accommodation Name",
    "vacation.accommodationPlaceholder": "e.g. Hotel Maria Cristina, Old Town Airbnb",
    "vacation.locationAddress": "Location / Address / Neighborhood",
    "vacation.pinOnMap": "Pin on Map",
    "vacation.searchVerify": "Search to verify location",
    "vacation.geoVerified": "Geo Verified",
    "vacation.checkInDay": "Check-in Day",
    "vacation.checkInHour": "Check-in Hour",
    "vacation.checkOutDay": "Check-out Day",
    "vacation.checkOutHour": "Check-out Hour",
    "vacation.accommodationNotes": "Description / Hotel Notes (Optional)",
    "vacation.accommodationNotesPlaceholder": "e.g. 10 min walk from train station, offers luggage storage",
    "vacation.remove": "Remove",
    "vacation.arrivalHour": "Arrival Hour (Day 1)",
    "vacation.arrivalHourDesc": "Day 1 starts after your arrival time.",
    "vacation.departureHour": "Departure Hour (Final Day)",
    "vacation.departureHourDesc": "Final day wraps up before your departure time.",
    "vacation.transport": "Means of Transport Available",
    "vacation.transportMulti": "Multiple Choice",
    "vacation.transportDesc": "Select all transportation options available during your trip:",
    "vacation.transportPublic": "Public Transit & Walking",
    "vacation.transportPublicDesc": "Local buses, trains & walking",
    "vacation.transportCar": "Private / Rental Car",
    "vacation.transportCarDesc": "Excursions & coastal drives",
    "vacation.transportBike": "Bicycle / E-Bike",
    "vacation.transportBikeDesc": "Bike paths & urban rides",
    "vacation.transportTaxi": "Taxi / Rideshare",
    "vacation.transportTaxiDesc": "Door-to-door city transfers",
    "vacation.duration": "Trip Duration",
    "vacation.pacing": "Exploration Pace",
    "vacation.paceRelaxed": "Relaxed",
    "vacation.paceBalanced": "Balanced",
    "vacation.pacePacked": "Packed",
    "vacation.vibes": "Travel Vibes & Interests",
    "vacation.vibesDesc": "Select all that apply",
    "vacation.swiper": "Activity Discovery Swiper",
    "vacation.swiperInteractive": "Interactive",
    "vacation.swiperDesc": "Review & swipe right on candidate spots (with photos, Google Maps opinions & links) before building the final itinerary.",
    "vacation.budget": "Budget Planning Mode",
    "vacation.budgetTier": "Subjective Tier",
    "vacation.budgetExact": "Exact Budget / Day / Person",
    "vacation.budgetSavvy": "Budget-Savvy",
    "vacation.budgetSavvyDesc": "Street food & free vistas",
    "vacation.budgetMid": "Balanced",
    "vacation.budgetMidDesc": "Cozy bistros & iconic spots",
    "vacation.budgetLuxury": "Luxury",
    "vacation.budgetLuxuryDesc": "Michelin stars & private tours",
    "vacation.perPersonDay": "/ person / day",
    "vacation.quickSelect": "Quick Select:",
    "vacation.estTotalBudget": "Estimated Total Budget:",
    "vacation.traveler": "traveler",
    "vacation.travelers": "travelers",
    "vacation.dayWord": "day",
    "vacation.daysWord": "days",
    "vacation.advancedNotes": "Additional traveler requests or dietary notes (Optional)",
    "vacation.advancedNotesPlaceholder": "e.g. Vegetarian pintxos, traveling with elderly parents, interested in modern architecture and surf breaks...",
    "vacation.generating": "Curating Itinerary...",
    "vacation.submitSwiper": "Launch Activity Discovery & Swiper →",
    "vacation.submitMulti": "Generate Multi-Destination Plan →",
    "vacation.submitSingle": "Generate {days}-Day Itinerary →",

    // Vibe options
    "vibe.gastro": "Gastronomy & Local Food",
    "vibe.excursions": "Regional Excursions & Viewpoints",
    "vibe.shopping": "Shopping & Local Boutiques",
    "vibe.scenic": "Scenic & Outdoors",
    "vibe.history": "History & Architecture",
    "vibe.family": "Family Friendly",
    "vibe.hiddenGems": "Hidden Gems / Non-Touristy",
    "vibe.budget": "Budget Friendly",
    "vibe.nightlife": "Nightlife & Bars",
    "vibe.art": "Art & Culture",
    "vibe.relaxation": "Relaxation & Wellness",

    // Hometown Form
    "hometown.title": "Hometown Local Guide",
    "hometown.subtitle": "Native resident outings with zero tourist traps, tuned to weather & free time.",
    "hometown.liveSearchBadge": "Real-Time Live Search: Concerts, Markets & Sports",
    "hometown.locationLabel": "Current Town or Neighborhood",
    "hometown.verifiedTown": "Verified Town Coordinates",
    "hometown.nativeResident": "Native Resident Mode",
    "hometown.useGps": "Use GPS",
    "hometown.radius": "Exploration Radius",
    "hometown.time": "Time Available Today",
    "hometown.timeQuick": "Quick",
    "hometown.timeQuickHours": "1-2 hours",
    "hometown.timeHalf": "Half-Day",
    "hometown.timeHalfHours": "3-5 hours",
    "hometown.timeFull": "Full Day",
    "hometown.timeFullHours": "All Day",
    "hometown.occasion": "Occasion & Desired Vibe",
    "hometown.weather": "Current Weather Context",
    "hometown.liveSensor": "Live Sensor Sync",
    "hometown.presets": "Presets...",
    "hometown.antiRepeat": "30-Day Anti-Repeat Memory Active",
    "hometown.antiRepeatDesc": "Automatically tracks history to prevent suggesting recently visited places",
    "hometown.manage": "Manage",
    "hometown.residentNotes": "Add Resident Specifics (Dog friendly, craft roastery, bike path)",
    "hometown.residentNotesHide": "Hide Resident Specifics",
    "hometown.discovering": "Scouting Local Gems within {radius}km...",
    "hometown.discoverBtn": "Discover Local Outing in {city}",

    // Occasions
    "occ.solo": "Solo Chill & Read",
    "occ.soloDesc": "Quiet roasteries, bookshops, parks",
    "occ.date": "Date Night & Ambiance",
    "occ.dateDesc": "Atmospheric bistros, sunset spots",
    "occ.adventure": "Outdoor Adventure",
    "occ.adventureDesc": "Scenic trails, viewpoints, riverbanks",
    "occ.rainy": "Rainy Day Indoor",
    "occ.rainyDesc": "Museums, cozy cafes, craft galleries",
    "occ.tapas": "Local Tapas & Eateries",
    "occ.tapasDesc": "Authentic hidden food counters",
    "occ.nature": "Nature & River Spots",
    "occ.natureDesc": "Green sanctuaries & wetlands",
    "occ.vintage": "Hidden Gems & Vintage",
    "occ.vintageDesc": "Indie vinyl, thrift, secret gardens",
    "occ.family": "Family Fun Outing",
    "occ.familyDesc": "Interactive parks & family treats",

    // Itinerary & Timeline
    "itinerary.budgetTier": "Budget Tier",
    "itinerary.pacing": "Pacing",
    "itinerary.pacing.relaxed": "Relaxed",
    "itinerary.pacing.balanced": "Balanced",
    "itinerary.pacing.packed": "Packed",
    "itinerary.totalBudget": "Est. Budget",
    "itinerary.transit": "Transit",
    "itinerary.morning": "Morning",
    "itinerary.afternoon": "Afternoon",
    "itinerary.evening": "Evening",
    "itinerary.night": "Night",
    "itinerary.mustSee": "Must See",
    "itinerary.hiddenGem": "Hidden Gem",
    "itinerary.culturalSignificance": "Cultural Significance",
    "itinerary.localTip": "Local Etiquette & Tip",
    "itinerary.weather": "Weather",
    "itinerary.walk": "walk",
    "itinerary.drive": "drive",
    "itinerary.taxi": "taxi",
    "itinerary.viewMap": "View Map & Transit",
    "itinerary.costPerPerson": "Est. Cost / Person",
    "itinerary.free": "Free",
    "itinerary.replaceActivity": "Swap Activity",
    "itinerary.deleteActivity": "Delete",
    "itinerary.moveUp": "Move Earlier",
    "itinerary.moveDown": "Move Later",
    "itinerary.markVisited": "Visited",
    "itinerary.markUnvisited": "Mark Visited",
    "itinerary.directions": "Google Maps Directions",
    "itinerary.reviews": "Verified Reviews & Tips",

    // Group Hub Modal
    "collab.title": "Group Travel Hub & Collaboration",
    "collab.subtitle": "Manage group access, day-by-day activity voting, luggage packing & Tricount expense splits",
    "collab.activeUser": "Active Traveler",
    "collab.rename": "Rename",
    "collab.addMember": "Add Traveler",
    "collab.tab.votes": "Activity Votes by Day",
    "collab.tab.packing": "Luggage & Packing",
    "collab.tab.expenses": "Tricount Expenses",
    "collab.tab.members": "Members & Access",
    "collab.consensus.title": "Itinerary Spot Consensus & Group Feedback",
    "collab.consensus.desc": "Vote on spots per day in chronological sequence so the group locks in consensus.",
    "collab.vote.mustDo": "Must-Do",
    "collab.vote.soundsGood": "Sounds Good",
    "collab.vote.pass": "Pass",
    "collab.packing.readiness": "{name}'s Luggage Readiness",
    "collab.packing.packed": "{packed} of {total} items packed",
    "collab.packing.add": "Add custom packing item...",
    "collab.expenses.totalSpend": "Total Group Spend",
    "collab.expenses.balances": "Tricount Member Net Balances",
    "collab.expenses.settlementPlan": "Optimal Debt Settlement Plan (Who Pays Whom)",
    "collab.expenses.addExpense": "+ Add New Expense",
    "collab.members.accessMode": "Group Access Permission Mode",
    "collab.members.inviteCode": "Trip Invite Code",

    // Schedule Adjuster
    "schedule.title": "Live Schedule Adjuster & Delay Recalibration",
    "schedule.subtitle": "Running late or ahead of time? Adjust your day with smart route recalculations",
    "schedule.runningAhead": "Running Ahead",
    "schedule.runningBehind": "Running Behind",
    "schedule.recalculate": "Apply New Schedule",
    "schedule.minutes": "minutes",
    "schedule.selectDay": "Select Day to Adjust:",
    "schedule.delayStart": "When has the delay started?",
    "schedule.delayStartDesc": "Activities before this remain untouched",
    "schedule.fromStart": "From the very start of the day (All activities)",
    "schedule.fromSpot": "Starting from Spot #{idx}: {time} — {name}",
    "schedule.offset": "Schedule Shift Offset:",
    "schedule.behind": "+{minutes} min (Behind Schedule)",
    "schedule.ahead": "{minutes} min (Ahead of Schedule)",
    "schedule.onSchedule": "On Schedule (0m)",
    "schedule.compress": "Compress Subsequent Spot Durations (Smart Catch-Up)",
    "schedule.compressDesc": "Automatically trims 10-15 minutes from later stops so your day doesn't run past dinner or closing hours.",
    "schedule.constraints": "Smart Schedule Constraints Detected:",
    "schedule.preview": "Schedule Recalibration Preview (Day {day}):",
    "schedule.allShifted": "All activities shifted",
    "schedule.shiftedFrom": "Shifted starting from spot #{spot}",
    "schedule.untouched": "Untouched",
    "schedule.original": "Original: {time}",
    "schedule.reset": "Reset to Original Schedule",
    "schedule.applyDay": "Apply Shift to Day {day}",

    // Pocket Offline Guide
    "pocket.title": "Offline Pocket Companion",
    "pocket.subtitle": "Ultra-lightweight offline view ready for airplane mode & low battery.",
    "pocket.downloadPdf": "Save PDF for Travel",
    "pocket.emergency": "Local Emergency & Basque Etiquette",
    "pocket.airplaneReady": "Airplane Mode Ready",
    "pocket.zeroInternet": "Zero Internet Required",
    "pocket.cached": "Cached in Browser Storage",
    "pocket.notCached": "Not Cached Yet",
    "pocket.visitedCount": "{count}/{total} Visited ({percent}%)",
    "pocket.cacheBtn": "💾 Cache Trip in Browser",
    "pocket.cachedBtn": "✓ Cached Offline",
    "pocket.downloadHtml": "Download HTML File",
    "pocket.tabChecklist": "📋 Pocket Checklist & Schedule",
    "pocket.tabNotes": "📝 Offline Notes & Memos",
    "pocket.tabEmergency": "🚨 Emergency & Offline Info",
    "pocket.showRemaining": "Showing Remaining",
    "pocket.showAll": "Show All",
    "pocket.allVisited": "🎉 All spots for this day have been visited!",
    "pocket.notesTip": "💡 Notes entered here are saved locally on your device and will be included inside your downloaded offline guide.",
    "pocket.notesPlaceholder": "Add door access codes, reservation numbers, emergency notes, metro card numbers, or local reminders here...",
    "pocket.emergencyTitle": "Important Emergency Hotlines",
    "pocket.emergencyDesc": "Save or write down these local contacts before embarking without internet:",
    "pocket.emergencyEU": "General Emergency (EU)",
    "pocket.medical": "Medical / Ambulance",
    "pocket.localPolice": "Local Police (Policía Local)",
    "pocket.nationalPolice": "National Police",
    "pocket.phrasesTitle": "Essential Local Phrases (Spanish / Basque)",
    "pocket.readyOffline": "Ready to explore {dest} offline",

    // Day Card
    "day.plannedSpots": "{count} planned spots",
    "day.mappedSpots": "{count} Mapped Spots",
    "day.estBudget": "Est. {budget}",
    "day.adjustSchedule": "Adjust Schedule / Running Late",
    "day.exportGoogleMaps": "Export Day Route to Google Maps",
    "day.directions": "Directions",
    "day.addCustomSpot": "Add Custom Spot to Day {day}",
    "day.deleteConfirm": "Delete Day {day}?",

    // Activity Card & Details
    "act.swap": "Swap Spot",
    "act.swapping": "Swapping...",
    "act.visited": "Visited",
    "act.markVisited": "Mark Visited",
    "act.details": "Details & Guide",
    "act.tickets": "Buy Tickets / Booking",
    "act.mapsReviews": "Map & Reviews",
    "act.notes": "Notes",
    "act.note": "Note",
    "act.reviews": "Reviews",
    "act.hideReviews": "Hide Reviews",
    "act.insiderTip": "Insider Note:",
    "act.groupNotesTitle": "Group Travel Notes & Tips",
    "act.noNotes": "No group notes left for this spot yet. Add a reservation confirmation, meeting point, or thought below!",
    "act.addNotePlaceholder": "Add note as {user}...",
    "act.permanentSkip": "Permanently Exclude Spot",
    "act.permanentSkipPrompt": "Never suggest \"{name}\" again?\n\nIt will be permanently excluded from all future plans. You can undo this anytime in History → Permanent Skips.",

    // Activity Deep Details Modal
    "detail.storyAndDetails": "Story & Details",
    "detail.exactLocation": "Exact Location & Pins",
    "detail.anecdotes": "Anecdotes & Lore",
    "detail.askGuide": "Ask Local Guide",
    "detail.aboutExperience": "About this Experience",
    "detail.historicalContext": "Historical Context & Roots",
    "detail.culturalSignificance": "Cultural Significance",
    "detail.visualHighlights": "Architectural & Visual Highlights",
    "detail.whatToExpect": "What to Expect",
    "detail.practicalGuide": "Practical Guide for Visitors",
    "detail.bestTimeToVisit": "Best Time to Visit",
    "detail.photographyTip": "Photography Tip",
    "detail.insiderSecret": "Insider Secret",
    "detail.chatCtaTitle": "Have a question about this spot?",
    "detail.chatCtaDesc": "Chat directly with your on-demand AI Local Guide for {spot}.",
    "detail.chatWithGuide": "Chat with Guide",
    "detail.exactCoords": "Exact Coordinates & Sub-Spot Route",
    "detail.openMaps": "Open Maps",
    "detail.mustVisitWithin": "Must-Visit Highlights Within this Area ({count} Key Stops)",
    "detail.whyStopHere": "Why stop here: ",
    "detail.singleLocation": "Single Location Spot",
    "detail.singleLocationDesc": "This activity is centered directly at this standalone venue or monument. The pin above highlights the primary entrance and meeting point.",
    "detail.anecdotesTitle": "Anecdotes, Legends & Local Lore",
    "detail.anecdotesDesc": "Fascinating historical occurrences, secret trivia, and oral traditions passed down through generations in {dest}.",
    "detail.quote": "Famous Quote",
    "detail.guideHeader": "Local Guide & Travel Agent",
    "detail.guideSub": "Live expert on {spot} in {dest}",
    "detail.guideHint": "Ask for quotes, history, secret dishes, or stories",
    "detail.thinking": "Thinking with local knowledge...",
    "detail.suggestedQuestions": "Suggested Follow-up Questions:",
    "detail.chatPlaceholder": "Ask about {spot}, history, anecdotes, or advice...",
    "detail.ask": "Ask",
    "detail.aiEnabled": "Worldwide dynamic AI exploration enabled",

    // Saved Trips Drawer
    "saved.title": "Saved Journeys",
    "saved.searchPlaceholder": "Search destination or trip name...",
    "saved.all": "All",
    "saved.vacations": "Vacations",
    "saved.hometown": "Hometown",
    "saved.noTrips": "No saved itineraries found",
    "saved.noTripsSub": "Plan a vacation or hometown outing and click \"Save Trip\" to store it offline.",
    "saved.openPlan": "Open Plan",

    // Categories
    "category.food": "Local Eatery",
    "category.nature": "Nature & Walk",
    "category.culture": "Culture & Art",
    "category.sightseeing": "Landmark",
    "category.hidden-gem": "Secret Spot",
    "category.shopping": "Artisan Craft",
    "category.relaxation": "Sanctuary",
    "category.nightlife": "Evening Spot",
    "category.cafe": "Local Roastery",
    "category.entertainment": "Entertainment",

    // Day transit and route
    "transit.walk": "{mins} min walk",
    "transit.transit": "{mins} min transit",
    "transit.drive": "{mins} min drive/taxi",
    "transit.connection": "{mins} min connection",
    "transit.pleasantWalk": "Pleasant walk ({dist}) through the neighborhood towards {dest}",
    "transit.instructions": "Direct connection from {from} to {to}",
    "transit.navigate": "Navigate from {from} to {to}",
    "transit.walkTo": "Walk ({dist}) to {dest}",

    // Extra Itinerary translations
    "itinerary.highlightsTitle": "Curated Highlights & Signatures",
    "itinerary.mapTitle": "Geographic Route & Activity Map",
    "itinerary.pinnedLocations": "Pinned Locations",
    "itinerary.customizedTitle": "Customized your schedule?",
    "itinerary.customizedDesc": "If you removed or retimed activities, the AI will keep all your choices and fill the open schedule slots with new local spots!",
    "itinerary.autoFillEmpty": "Auto-Fill Empty Slots",
    "itinerary.geoVerified": "✓ Geo Verified",
    "itinerary.checkIn": "Check-in: Day {day}",
    "itinerary.checkOut": "Check-out: Day {day}",

    // Taste Profile Popup
    "taste.title": "Taste Profile",
    "taste.subtitle": "Tell the AI how you like to eat & drink — suggestions adapt to you and to each day's plan",
    "taste.explanation": "The AI uses this profile to pick bars, cafés and restaurants that fit you — and pairs them with the flow of the day (a casual counter after a hike, a terrace before a sunset stroll, somewhere cozy on a rainy museum day).",
    "taste.diningLabel": "How do you like to eat?",
    "taste.drinkLabel": "What do you like to drink?",
    "taste.atmosphereLabel": "What atmosphere do you enjoy?",
    "taste.dislikesLabel": "What should be avoided?",
    "taste.budgetLabel": "Usual food & drink budget",
    "taste.dietaryLabel": "Dietary notes",
    "taste.selectAll": "Select all that apply",
    "taste.avoidHint": "The AI will steer clear of these",
    "taste.optional": "Optional",
    "taste.clear": "Clear profile",
    "taste.save": "Save Taste Profile",
    "taste.saved": "Saved",
    "taste.placeholder": "e.g. Vegetarian, gluten-free, love spicy food, allergic to shellfish…",
    "taste.clearConfirm": "Clear your taste profile? Dining suggestions will no longer be personalized.",

    // Taste options details
    "taste.style.pintxo": "Pintxo / tapas hopping",
    "taste.style.sitdown": "Sit-down local restaurant",
    "taste.style.market": "Market counter & stalls",
    "taste.style.quick": "Quick bites & street food",
    "taste.style.tasting": "Long gastronomic tasting",
    "taste.style.picnic": "Picnic & takeaway",
    "taste.drink.coffee": "Specialty coffee",
    "taste.drink.wine": "Local wine / txakoli",
    "taste.drink.beer": "Craft beer",
    "taste.drink.cocktails": "Cocktails & mixed drinks",
    "taste.drink.cider": "Cider (sagardotegi style)",
    "taste.drink.tea": "Tea & infusions",
    "taste.drink.nonalcoholic": "Alcohol-free options",
    "taste.atmosphere.quiet": "Quiet & cozy",
    "taste.atmosphere.lively": "Lively & social",
    "taste.atmosphere.terrace": "Terrace / outdoor seating",
    "taste.atmosphere.historic": "Historic & classic",
    "taste.atmosphere.modern": "Modern & trendy",
    "taste.atmosphere.family": "Family-friendly",
    "taste.dislike.tourist": "Tourist traps",
    "taste.dislike.chains": "Chains & franchises",
    "taste.dislike.queues": "Long queues",
    "taste.dislike.loud": "Loud music",
    "taste.dislike.crowded": "Overcrowded places",
    "taste.budget.easy": "Easy-going",
    "taste.budget.easyDesc": "Counters, daily menus",
    "taste.budget.balanced": "Balanced",
    "taste.budget.balancedDesc": "Good food, fair price",
    "taste.budget.luxury": "Treat myself",
    "taste.budget.luxuryDesc": "High-end experiences",

    // My Places Popup
    "spots.title": "My Places",
    "spots.subtitle": "Your own bars, cafés & restaurants — the only source for dining recommendations",
    "spots.explanation": "LocalExplorer never invents bars, cafés or restaurants from a built-in list. Dining suggestions come from places you add here or from live AI search — everything is located dynamically on the map.",
    "spots.category.bar": "Bar",
    "spots.category.cafe": "Café",
    "spots.category.restaurant": "Restaurant",
    "spots.category.other": "Other favorite",
    "spots.formName": "Place name *",
    "spots.formType": "Type",
    "spots.formTown": "Town / Area",
    "spots.formNote": "Note (optional)",
    "spots.placeholderName": "e.g. Bar Iruña, Kafé Bergara…",
    "spots.placeholderTown": "e.g. Bilbao, Spain",
    "spots.placeholderNote": "e.g. best tortilla on Fridays",
    "spots.btnSaving": "Locating…",
    "spots.btnAdd": "Add Place",
    "spots.empty": "No places saved yet",
    "spots.emptyDesc": "Add your favorite café, bar or restaurant above and plans will be built around them.",
    "spots.located": "located",
    "spots.pending": "pending location",
    "spots.footer": "{count} places saved — they power your dining recommendations",
    "spots.done": "Done",
    "spots.addSuccess": "Added and located on the map.",
    "spots.addWarn": "Added, but could not locate it right now. It will be geocoded again when it gets recommended.",
    "spots.deleteConfirm": "Remove this place?",

    // Memory & Exclusions Popup (History)
    "history.title": "Memory & Exclusions",
    "history.subtitle": "What LocalExplorer AI remembers — and what it must never suggest again",
    "history.tabMemory": "30-Day Memory ({count})",
    "history.tabSkips": "Permanent Skips ({count})",
    "history.memoryDesc": "To keep your adventures fresh, LocalExplorer AI remembers suggested spots and hides them for 30 days. Remove individual spots below if you'd like them re-suggested sooner.",
    "history.skipsDesc": "Places you never want suggested again — anywhere, ever. Add to this list with the Ban button on any activity, or remove entries below to allow them back.",
    "history.noHistory": "No activity history yet",
    "history.noHistorySub": "As you explore local itineraries, suggested spots are logged here.",
    "history.noSkips": "No permanent exclusions",
    "history.noSkipsSub": "Use the Ban button on any activity card (\"never suggest again\") and it will be excluded from every future plan.",
    "history.spotsTracked": "{count} spots tracked",
    "history.resetMemory": "Reset Memory (Clear All)",
    "history.skipsCount": "{count} places permanently excluded",
    "history.clearConfirm": "Clear all 30-day activity history? The app will reset the anti-repeat memory filter.",
    "history.today": "Today",
    "history.daysAgo": "{days}d ago",
    "history.excluded": "Excluded forever",
    "history.addedOn": "added {date}",

    // Extra Activity actions
    "act.multipleChoice": "Multiple Choice Options (Click to switch)",
    "act.available": "{count} Available",
    "act.freshChoice": "Fresh Choice 🔄",
    "act.deleteConfirm": "Remove \"{name}\" from Day {day}?",
    "act.liveHappening": "Live Happening 🔥",
    "act.activeEvent": "Active Local Event",
    "act.venue": "Venue: {venue}",

  },

  es: {
    // Navigation & Header
    "nav.brand": "LocalExplorer AI",
    "nav.subtitle": "Planificador de Viajes Culturales y Guía Local",
    "nav.vacation": "Vacaciones",
    "nav.hometown": "Ciudad Local",
    "nav.tasteProfile": "Perfil Gastronómico",
    "nav.mySpots": "Mis Lugares",
    "nav.history": "Historial",
    "nav.savedTrips": "Guardados",
    "nav.syncReady": "Sincronizado",
    "nav.saving": "Guardando...",
    "nav.offline": "Offline",
    "nav.cached": "En Caché",

    // Actions & Tools
    "action.saveTrip": "Guardar Viaje",
    "action.saved": "Guardado",
    "action.share": "Compartir",
    "action.export": "Exportar",
    "action.print": "Imprimir Mapas",
    "action.groupHub": "Hub de Grupo",
    "action.pocketGuide": "Guía de Bolsillo",
    "action.adjustSchedule": "Ajustar Horario",
    "action.liveNavigator": "Navegador en Vivo",
    "action.regenerate": "Regenerar Todo",
    "action.reiterate": "Ajustar Itinerario",
    "action.addActivity": "Añadir Actividad",
    "action.allDays": "Todos los Días",
    "action.day": "Día",
    "action.days": "Días",
    "action.close": "Cerrar",
    "action.cancel": "Cancelar",
    "action.save": "Guardar",
    "action.delete": "Eliminar",
    "action.edit": "Editar",
    "action.copyLink": "Copiar Enlace de Invitación",
    "action.copyCode": "Copiar Código",

    // Vacation Form
    "vacation.title": "Planificador de Itinerarios de Vacaciones",
    "vacation.subtitle": "Itinerarios culturales de varios días con joyas ocultas auténticas y optimización de rutas verificada",
    "vacation.tripMode": "Modo de Viaje:",
    "vacation.singleDest": "Destino Único",
    "vacation.multiDest": "Multi-Destino / En Ruta",
    "vacation.destinationLabel": "Ciudad o Región de Destino (Asesor y Verificador)",
    "vacation.geocoding": "Geolocalización Precisa",
    "vacation.popular": "Populares:",
    "vacation.multiCityStops": "Paradas de la Ruta Multi-Ciudad",
    "vacation.stop": "Parada",
    "vacation.addStop": "Añadir Otra Parada / Ciudad",
    "vacation.groupSize": "Tamaño del Grupo de Viaje",
    "vacation.groupSizeDesc": "Número de personas que viajan en tu grupo",
    "vacation.person": "Persona",
    "vacation.people": "Personas",
    "vacation.solo": "Viajero Solo",
    "vacation.couple": "Pareja (2)",
    "vacation.smallGroup": "Grupo Pequeño (4)",
    "vacation.largeGroup": "Grupo Grande (6+)",
    "vacation.accommodationTitle": "Alojamiento Reservado y Estancia",
    "vacation.accommodationSubtitle": "Especifica hoteles, días y horas de entrada y salida para estancias únicas o en ruta",
    "vacation.accommodationHeading": "Alojamientos Reservados y Estancia",
    "vacation.accommodationSub": "Define puntos de salida/llegada diarios, días y horas de check-in y check-out",
    "vacation.showAccommodation": "Mostrar Alojamiento",
    "vacation.hideAccommodation": "Ocultar Alojamiento",
    "vacation.addStay": "Añadir Otra Estancia",
    "vacation.stay": "Estancia",
    "vacation.accommodationName": "Nombre del Alojamiento",
    "vacation.accommodationPlaceholder": "ej. Hotel Maria Cristina, Apartamento Parte Vieja",
    "vacation.locationAddress": "Ubicación / Dirección / Barrio",
    "vacation.pinOnMap": "Fijar en Mapa",
    "vacation.searchVerify": "Busca para verificar ubicación",
    "vacation.geoVerified": "Geo Verificado",
    "vacation.checkInDay": "Día de Entrada",
    "vacation.checkInHour": "Hora de Entrada",
    "vacation.checkOutDay": "Día de Salida",
    "vacation.checkOutHour": "Hora de Salida",
    "vacation.accommodationNotes": "Descripción / Notas del Hotel (Opcional)",
    "vacation.accommodationNotesPlaceholder": "ej. A 10 min a pie de la estación, permite dejar maletas",
    "vacation.remove": "Eliminar",
    "vacation.arrivalHour": "Hora de Llegada (Día 1)",
    "vacation.arrivalHourDesc": "El día 1 comenzará tras tu hora de llegada.",
    "vacation.departureHour": "Hora de Salida (Último Día)",
    "vacation.departureHourDesc": "El último día concluirá antes de tu hora de salida.",
    "vacation.transport": "Medios de Transporte Disponibles",
    "vacation.transportMulti": "Opción Múltiple",
    "vacation.transportDesc": "Selecciona todos los transportes que tendrás a tu disposición:",
    "vacation.transportPublic": "Transporte Público y a Pie",
    "vacation.transportPublicDesc": "Autobuses locales, trenes y paseos",
    "vacation.transportCar": "Coche Propio / Alquiler",
    "vacation.transportCarDesc": "Excursiones y rutas costeras",
    "vacation.transportBike": "Bicicleta / Bici Eléctrica",
    "vacation.transportBikeDesc": "Bidegorris y paseos urbanos",
    "vacation.transportTaxi": "Taxi / VTC",
    "vacation.transportTaxiDesc": "Traslados puerta a puerta",
    "vacation.duration": "Duración del Viaje",
    "vacation.pacing": "Ritmo de Exploración",
    "vacation.paceRelaxed": "Relajado",
    "vacation.paceBalanced": "Equilibrado",
    "vacation.pacePacked": "Intenso",
    "vacation.vibes": "Estilo de Viaje e Intereses",
    "vacation.vibesDesc": "Selecciona todos los que apliquen",
    "vacation.swiper": "Descubridor de Actividades",
    "vacation.swiperInteractive": "Interactivo",
    "vacation.swiperDesc": "Revisa y desliza a la derecha en los lugares candidatos (con fotos y opiniones) antes de generar el plan final.",
    "vacation.budget": "Modo de Presupuesto",
    "vacation.budgetTier": "Categoría General",
    "vacation.budgetExact": "Presupuesto Exacto / Día / Persona",
    "vacation.budgetSavvy": "Económico",
    "vacation.budgetSavvyDesc": "Comida local y miradores libres",
    "vacation.budgetMid": "Equilibrado",
    "vacation.budgetMidDesc": "Bistrós acogedores y lugares icónicos",
    "vacation.budgetLuxury": "Lujo",
    "vacation.budgetLuxuryDesc": "Estrellas Michelin y visitas privadas",
    "vacation.perPersonDay": "/ persona / día",
    "vacation.quickSelect": "Selección Rápida:",
    "vacation.estTotalBudget": "Presupuesto Total Estimado:",
    "vacation.traveler": "viajero",
    "vacation.travelers": "viajeros",
    "vacation.dayWord": "día",
    "vacation.daysWord": "días",
    "vacation.advancedNotes": "Peticiones adicionales o notas dietéticas (Opcional)",
    "vacation.advancedNotesPlaceholder": "ej. Pintxos vegetarianos, viajamos con personas mayores, interesados en arquitectura y surf...",
    "vacation.generating": "Diseñando Itinerario...",
    "vacation.submitSwiper": "Abrir Descubridor de Actividades →",
    "vacation.submitMulti": "Generar Plan Multi-Destino →",
    "vacation.submitSingle": "Generar Itinerario de {days} Días →",

    // Vibe options
    "vibe.gastro": "Gastronomía y Pintxos Locales",
    "vibe.excursions": "Excursiones Regionales y Miradores",
    "vibe.shopping": "Compras y Boutiques Locales",
    "vibe.scenic": "Naturaleza y Aire Libre",
    "vibe.history": "Historia y Arquitectura",
    "vibe.family": "Ideal para Familias",
    "vibe.hiddenGems": "Joyas Ocultas / Sin Turistas",
    "vibe.budget": "Económico / Low Cost",
    "vibe.nightlife": "Vida Nocturna y Bares",
    "vibe.art": "Arte y Cultura",
    "vibe.relaxation": "Relax y Bienestar",

    // Hometown Form
    "hometown.title": "Guía Local de Ciudad",
    "hometown.subtitle": "Planes de residente auténtico sin trampas para turistas, adaptados al clima y tu tiempo libre.",
    "hometown.liveSearchBadge": "Búsqueda en Vivo: Conciertos, Mercadillos y Deportes",
    "hometown.locationLabel": "Ciudad, Pueblo o Barrio Actual",
    "hometown.verifiedTown": "Coordenadas Verificadas",
    "hometown.nativeResident": "Modo Residente Nativo",
    "hometown.useGps": "Usar GPS",
    "hometown.radius": "Radio de Exploración",
    "hometown.time": "Tiempo Disponible Hoy",
    "hometown.timeQuick": "Rápido",
    "hometown.timeQuickHours": "1-2 horas",
    "hometown.timeHalf": "Media Jornada",
    "hometown.timeHalfHours": "3-5 horas",
    "hometown.timeFull": "Día Completo",
    "hometown.timeFullHours": "Todo el Día",
    "hometown.occasion": "Ocasión y Ambiente Deseado",
    "hometown.weather": "Contexto del Clima Actual",
    "hometown.liveSensor": "Sensor en Vivo",
    "hometown.presets": "Preajustes...",
    "hometown.antiRepeat": "Memoria Anti-Repetición de 30 Días Activa",
    "hometown.antiRepeatDesc": "Rastrea el historial automáticamente para evitar sugerir lugares visitados recientemente",
    "hometown.manage": "Gestionar",
    "hometown.residentNotes": "Añadir Detalles de Residente (Admite perros, café de especialidad, bidegorri)",
    "hometown.residentNotesHide": "Ocultar Detalles de Residente",
    "hometown.discovering": "Buscando Joyas Locales en {radius}km...",
    "hometown.discoverBtn": "Descubrir Plan Local en {city}",

    // Occasions
    "occ.solo": "Lectura y Relax en Solitario",
    "occ.soloDesc": "Cafés tranquilos, librerías, parques",
    "occ.date": "Cita y Ambiente Nocturno",
    "occ.dateDesc": "Bistrós con encanto, puestas de sol",
    "occ.adventure": "Aventura al Aire Libre",
    "occ.adventureDesc": "Senderos panorámicos, orillas del río",
    "occ.rainy": "Plan de Interior para Día Lluvioso",
    "occ.rainyDesc": "Museos, cafés acogedores, galerías",
    "occ.tapas": "Ruta de Pintxos y Tabernas",
    "occ.tapasDesc": "Barras gastronómicas auténticas",
    "occ.nature": "Naturaleza y Zonas Verdes",
    "occ.natureDesc": "Santuarios naturales y humedales",
    "occ.vintage": "Joyas Ocultas y Vintage",
    "occ.vintageDesc": "Vinilos indie, tiendas retro, jardines",
    "occ.family": "Plan Familiar con Niños",
    "occ.familyDesc": "Parques interactivos y meriendas",

    // Itinerary & Timeline
    "itinerary.budgetTier": "Nivel de Presupuesto",
    "itinerary.pacing": "Ritmo",
    "itinerary.pacing.relaxed": "Relajado",
    "itinerary.pacing.balanced": "Equilibrado",
    "itinerary.pacing.packed": "Intenso",
    "itinerary.totalBudget": "Presupuesto Est.",
    "itinerary.transit": "Transporte",
    "itinerary.morning": "Mañana",
    "itinerary.afternoon": "Tarde",
    "itinerary.evening": "Atardecer / Noche",
    "itinerary.night": "Noche",
    "itinerary.mustSee": "Imprescindible",
    "itinerary.hiddenGem": "Joya Oculta",
    "itinerary.culturalSignificance": "Relevancia Cultural",
    "itinerary.localTip": "Etiqueta y Consejo Local",
    "itinerary.weather": "Clima",
    "itinerary.walk": "a pie",
    "itinerary.drive": "en coche",
    "itinerary.taxi": "taxi",
    "itinerary.viewMap": "Ver Mapa y Trayectos",
    "itinerary.costPerPerson": "Coste Est. / Persona",
    "itinerary.free": "Gratis",
    "itinerary.replaceActivity": "Cambiar Actividad",
    "itinerary.deleteActivity": "Eliminar",
    "itinerary.moveUp": "Mover Antes",
    "itinerary.moveDown": "Mover Después",
    "itinerary.markVisited": "Visitado",
    "itinerary.markUnvisited": "Marcar Visitado",
    "itinerary.directions": "Cómo Llegar (Google Maps)",
    "itinerary.reviews": "Opiniones y Consejos Verificados",

    // Group Hub Modal
    "collab.title": "Hub de Viaje en Grupo y Colaboración",
    "collab.subtitle": "Gestiona acceso grupal, votación diaria de actividades, equipaje y gastos Tricount",
    "collab.activeUser": "Viajero Activo",
    "collab.rename": "Renombrar",
    "collab.addMember": "Añadir Viajero",
    "collab.tab.votes": "Votación de Actividades",
    "collab.tab.packing": "Equipaje y Maletas",
    "collab.tab.expenses": "Gastos Tricount",
    "collab.tab.members": "Miembros y Acceso",
    "collab.consensus.title": "Consenso y Votos del Grupo por Día",
    "collab.consensus.desc": "Vota las actividades cronológicamente para definir el plan común del grupo.",
    "collab.vote.mustDo": "Imprescindible",
    "collab.vote.soundsGood": "Me gusta",
    "collab.vote.pass": "Pasar",
    "collab.packing.readiness": "Preparación de Equipaje de {name}",
    "collab.packing.packed": "{packed} de {total} artículos empacados",
    "collab.packing.add": "Añadir artículo personalizado...",
    "collab.expenses.totalSpend": "Gasto Total del Grupo",
    "collab.expenses.balances": "Balances Netos Tricount",
    "collab.expenses.settlementPlan": "Plan Óptimo de Liquidación (Quién paga a quién)",
    "collab.expenses.addExpense": "+ Registrar Nuevo Gasto",
    "collab.members.accessMode": "Modo de Permisos de Acceso",
    "collab.members.inviteCode": "Código de Invitación",

    // Schedule Adjuster
    "schedule.title": "Ajustador de Horarios y Recalibración en Vivo",
    "schedule.subtitle": "¿Vas con retraso o adelantado? Ajusta tu día con recálculo inteligente de rutas",
    "schedule.runningAhead": "Adelantado",
    "schedule.runningBehind": "Con Retraso",
    "schedule.recalculate": "Aplicar Nuevo Horario",
    "schedule.minutes": "minutos",
    "schedule.selectDay": "Seleccionar Día para Ajustar:",
    "schedule.delayStart": "¿A partir de qué momento empezó el cambio?",
    "schedule.delayStartDesc": "Las actividades anteriores no se modificarán",
    "schedule.fromStart": "Desde el inicio del día (Todas las actividades)",
    "schedule.fromSpot": "A partir del lugar #{idx}: {time} — {name}",
    "schedule.offset": "Desplazamiento del Horario:",
    "schedule.behind": "+{minutes} min (Con retraso)",
    "schedule.ahead": "{minutes} min (Adelantado)",
    "schedule.onSchedule": "En Horario (0m)",
    "schedule.compress": "Comprimir duración de paradas posteriores (Ajuste Rápido)",
    "schedule.compressDesc": "Reduce automáticamente 10-15 min de paradas posteriores para no pasar de la cena o cierre.",
    "schedule.constraints": "Restricciones y Avisos de Horario Detectados:",
    "schedule.preview": "Vista Previa de Recalibración (Día {day}):",
    "schedule.allShifted": "Todas las actividades ajustadas",
    "schedule.shiftedFrom": "Ajustado a partir del lugar #{spot}",
    "schedule.untouched": "Sin cambios",
    "schedule.original": "Original: {time}",
    "schedule.reset": "Restablecer al Horario Original",
    "schedule.applyDay": "Aplicar Ajuste al Día {day}",

    // Pocket Offline Guide
    "pocket.title": "Guía de Bolsillo Offline",
    "pocket.subtitle": "Vista ultraligera pensada para modo avión y ahorro de batería.",
    "pocket.downloadPdf": "Guardar PDF de Viaje",
    "pocket.emergency": "Emergencias Locales y Consejos Culturales",
    "pocket.airplaneReady": "Listo para Modo Avión",
    "pocket.zeroInternet": "Cero Internet Requerido",
    "pocket.cached": "Guardado en Almacenamiento Local",
    "pocket.notCached": "Aún no guardado offline",
    "pocket.visitedCount": "{count}/{total} Visitados ({percent}%)",
    "pocket.cacheBtn": "💾 Guardar Viaje Offline",
    "pocket.cachedBtn": "✓ Guardado Offline",
    "pocket.downloadHtml": "Descargar Archivo HTML",
    "pocket.tabChecklist": "📋 Lista y Horario de Bolsillo",
    "pocket.tabNotes": "📝 Notas y Memos Offline",
    "pocket.tabEmergency": "🚨 Emergencias e Info Offline",
    "pocket.showRemaining": "Mostrando Pendientes",
    "pocket.showAll": "Mostrar Todos",
    "pocket.allVisited": "🎉 ¡Todos los lugares de este día han sido visitados!",
    "pocket.notesTip": "💡 Las notas introducidas aquí se guardan localmente en tu dispositivo y se incluirán en tu guía descargada.",
    "pocket.notesPlaceholder": "Añade códigos de puerta, reservas, teléfonos de emergencia, números de tarjeta de transporte o recordatorios...",
    "pocket.emergencyTitle": "Teléfonos de Emergencia Clave",
    "pocket.emergencyDesc": "Guarda o anota estos contactos antes de salir sin cobertura o internet:",
    "pocket.emergencyEU": "Emergencias Generales (UE)",
    "pocket.medical": "Urgencias Médicas / Ambulancia",
    "pocket.localPolice": "Policía Local",
    "pocket.nationalPolice": "Policía Nacional",
    "pocket.phrasesTitle": "Frases Locales Esenciales (Español / Euskera)",
    "pocket.readyOffline": "Listo para explorar {dest} sin conexión",

    // Day Card
    "day.plannedSpots": "{count} lugares planificados",
    "day.mappedSpots": "{count} Lugares Mapeados",
    "day.estBudget": "Est. {budget}",
    "day.adjustSchedule": "Ajustar Horario / Con Retraso",
    "day.exportGoogleMaps": "Exportar Ruta del Día a Google Maps",
    "day.directions": "Cómo Llegar",
    "day.addCustomSpot": "Añadir Lugar Personalizado al Día {day}",
    "day.deleteConfirm": "¿Eliminar Día {day}?",

    // Activity Card & Details
    "act.swap": "Cambiar Lugar",
    "act.swapping": "Cambiando...",
    "act.visited": "Visitado",
    "act.markVisited": "Marcar Visitado",
    "act.details": "Detalles y Guía",
    "act.tickets": "Comprar Entradas / Reserva",
    "act.mapsReviews": "Mapa y Opiniones",
    "act.notes": "Notas",
    "act.note": "Nota",
    "act.reviews": "Opiniones",
    "act.hideReviews": "Ocultar Opiniones",
    "act.insiderTip": "Consejo Local:",
    "act.groupNotesTitle": "Notas y Consejos del Grupo",
    "act.noNotes": "Aún no hay notas para este lugar. Añade reservas, puntos de encuentro o ideas.",
    "act.addNotePlaceholder": "Añadir nota como {user}...",
    "act.permanentSkip": "Excluir Lugar Permanentemente",
    "act.permanentSkipPrompt": "¿No sugerir \"{name}\" nunca más?\n\nSe excluirá permanentemente de todos los futuros planes.",

    // Activity Deep Details Modal
    "detail.storyAndDetails": "Historia y Detalles",
    "detail.exactLocation": "Ubicación Exacta y Puntos",
    "detail.anecdotes": "Anécdotas y Tradición",
    "detail.askGuide": "Preguntar al Guía",
    "detail.aboutExperience": "Sobre esta Experiencia",
    "detail.historicalContext": "Contexto Histórico y Raíces",
    "detail.culturalSignificance": "Significado Cultural",
    "detail.visualHighlights": "Puntos Destacados Arquitectónicos y Visuales",
    "detail.whatToExpect": "Qué Esperar",
    "detail.practicalGuide": "Guía Práctica para Visitantes",
    "detail.bestTimeToVisit": "Mejor Momento para Visitar",
    "detail.photographyTip": "Consejo Fotográfico",
    "detail.insiderSecret": "Secreto Local",
    "detail.chatCtaTitle": "¿Tienes alguna duda sobre este lugar?",
    "detail.chatCtaDesc": "Chatea directamente con tu Guía Local IA sobre {spot}.",
    "detail.chatWithGuide": "Chatear con el Guía",
    "detail.exactCoords": "Coordenadas Exactas y Ruta Interior",
    "detail.openMaps": "Abrir en Maps",
    "detail.mustVisitWithin": "Paradas Imprescindibles en esta Zona ({count} Puntos Clave)",
    "detail.whyStopHere": "Por qué parar aquí: ",
    "detail.singleLocation": "Ubicación Única",
    "detail.singleLocationDesc": "Esta actividad se centra en este monumento o local independiente. El mapa indica la entrada principal y punto de encuentro.",
    "detail.anecdotesTitle": "Anécdotas, Leyendas y Tradición Oral",
    "detail.anecdotesDesc": "Acontecimientos históricos fascinantes, curiosidades y leyendas transmitidas de generación en generación en {dest}.",
    "detail.quote": "Cita Célebre",
    "detail.guideHeader": "Guía Local y Agente de Viajes",
    "detail.guideSub": "Experto en vivo sobre {spot} en {dest}",
    "detail.guideHint": "Pregunta por citas, historia, platos típicos o relatos",
    "detail.thinking": "Consultando conocimiento local...",
    "detail.suggestedQuestions": "Preguntas de Seguimiento Sugeridas:",
    "detail.chatPlaceholder": "Pregunta sobre {spot}, historia, anécdotas o consejos...",
    "detail.ask": "Preguntar",
    "detail.aiEnabled": "Exploración dinámica con IA habilitada",

    // Saved Trips Drawer
    "saved.title": "Viajes Guardados",
    "saved.searchPlaceholder": "Buscar destino o nombre de viaje...",
    "saved.all": "Todos",
    "saved.vacations": "Vacaciones",
    "saved.hometown": "Ciudad Local",
    "saved.noTrips": "No hay itinerarios guardados",
    "saved.noTripsSub": "Diseña un viaje o salida local y pulsa \"Guardar Viaje\" para almacenarlo.",
    "saved.openPlan": "Abrir Plan",

    // Categories
    "category.food": "Restaurante Local",
    "category.nature": "Naturaleza y Paseo",
    "category.culture": "Cultura y Arte",
    "category.sightseeing": "Punto de Interés",
    "category.hidden-gem": "Rincón Secreto",
    "category.shopping": "Artesanía Local",
    "category.relaxation": "Santuario de Relax",
    "category.nightlife": "Vida Nocturna",
    "category.cafe": "Cafetería Local",
    "category.entertainment": "Entretenimiento",

    // Day transit and route
    "transit.walk": "{mins} min a pie",
    "transit.transit": "{mins} min en transporte",
    "transit.drive": "{mins} min en coche/taxi",
    "transit.connection": "{mins} min de conexión",
    "transit.pleasantWalk": "Agradable paseo ({dist}) por el barrio hacia {dest}",
    "transit.instructions": "Conexión directa desde {from} hasta {to}",
    "transit.navigate": "Navegar desde {from} hasta {to}",
    "transit.walkTo": "Caminar ({dist}) hasta {dest}",

    // Extra Itinerary translations
    "itinerary.highlightsTitle": "Destacados y Firmas Recomendadas",
    "itinerary.mapTitle": "Ruta Geográfica y Mapa de Actividades",
    "itinerary.pinnedLocations": "Ubicaciones Fijadas",
    "itinerary.customizedTitle": "¿Has personalizado tu horario?",
    "itinerary.customizedDesc": "Si has eliminado o reprogramado actividades, la IA mantendrá tus elecciones y rellenará los huecos vacíos con nuevos lugares locales.",
    "itinerary.autoFillEmpty": "Auto-Rellenar Huecos",
    "itinerary.geoVerified": "✓ Geo Verificado",
    "itinerary.checkIn": "Entrada: Día {day}",
    "itinerary.checkOut": "Salida: Día {day}",

    // Taste Profile Popup
    "taste.title": "Perfil Gastronómico",
    "taste.subtitle": "Cuéntale a la IA cómo te gusta comer y beber — las sugerencias se adaptarán a ti y al plan de cada día",
    "taste.explanation": "La IA utiliza este perfil para elegir bares, cafeterías y restaurantes que se adapten a ti, combinándolos con el ritmo del día (una barra informal después de una caminata, una terraza antes de un paseo al atardecer, un rincón acogedor en un día lluvioso de museos).",
    "taste.diningLabel": "¿Cómo te gusta comer?",
    "taste.drinkLabel": "¿Qué te gusta beber?",
    "taste.atmosphereLabel": "¿Qué ambiente disfrutas?",
    "taste.dislikesLabel": "¿Qué se debe evitar?",
    "taste.budgetLabel": "Presupuesto habitual para comer",
    "taste.dietaryLabel": "Notas dietéticas",
    "taste.selectAll": "Selecciona todo lo que aplique",
    "taste.avoidHint": "La IA evitará estos por completo",
    "taste.optional": "Opcional",
    "taste.clear": "Borrar perfil",
    "taste.save": "Guardar Perfil",
    "taste.saved": "Guardado",
    "taste.placeholder": "ej. Vegetariano, sin gluten, me encanta el picante, alérgico al marisco…",
    "taste.clearConfirm": "¿Borrar tu perfil gastronómico? Las sugerencias de comida ya no estarán personalizadas.",

    // Taste options details
    "taste.style.pintxo": "Tapeo / pintxos",
    "taste.style.sitdown": "Restaurante de mesa",
    "taste.style.market": "Puestos de mercado",
    "taste.style.quick": "Comida rápida / callejera",
    "taste.style.tasting": "Menú degustación largo",
    "taste.style.picnic": "Picnic / para llevar",
    "taste.drink.coffee": "Café de especialidad",
    "taste.drink.wine": "Vino local / txakolí",
    "taste.drink.beer": "Cerveza artesanal",
    "taste.drink.cocktails": "Cócteles y combinados",
    "taste.drink.cider": "Sidra (estilo sagardotegi)",
    "taste.drink.tea": "Té e infusiones",
    "taste.drink.nonalcoholic": "Opciones sin alcohol",
    "taste.atmosphere.quiet": "Tranquilo y acogedor",
    "taste.atmosphere.lively": "Animado y social",
    "taste.atmosphere.terrace": "Terraza / al aire libre",
    "taste.atmosphere.historic": "Histórico y clásico",
    "taste.atmosphere.modern": "Moderno y de moda",
    "taste.atmosphere.family": "Ambiente familiar",
    "taste.dislike.tourist": "Trampas para turistas",
    "taste.dislike.chains": "Cadenas y franquicias",
    "taste.dislike.queues": "Largas colas",
    "taste.dislike.loud": "Música alta",
    "taste.dislike.crowded": "Lugares abarrotados",
    "taste.budget.easy": "Económico",
    "taste.budget.easyDesc": "Barras, menús del día",
    "taste.budget.balanced": "Equilibrado",
    "taste.budget.balancedDesc": "Buena comida, precio justo",
    "taste.budget.luxury": "Darse un capricho",
    "taste.budget.luxuryDesc": "Experiencias de alta gama",

    // My Places Popup
    "spots.title": "Mis Lugares",
    "spots.subtitle": "Tus propios bares, cafeterías y restaurantes — la única fuente para recomendaciones de comida",
    "spots.explanation": "LocalExplorer nunca se inventa bares, cafeterías o restaurantes de una lista genérica. Las sugerencias de comida provienen de los lugares que agregas aquí o de la búsqueda de la IA en tiempo real; todo se localiza dinámicamente en el mapa.",
    "spots.category.bar": "Bar",
    "spots.category.cafe": "Cafetería",
    "spots.category.restaurant": "Restaurante",
    "spots.category.other": "Otro favorito",
    "spots.formName": "Nombre del lugar *",
    "spots.formType": "Tipo",
    "spots.formTown": "Población / Zona",
    "spots.formNote": "Nota (opcional)",
    "spots.placeholderName": "ej. Bar Iruña, Kafé Bergara…",
    "spots.placeholderTown": "ej. Bilbao, España",
    "spots.placeholderNote": "ej. la mejor tortilla los viernes",
    "spots.btnSaving": "Localizando…",
    "spots.btnAdd": "Añadir Lugar",
    "spots.empty": "Aún no hay lugares guardados",
    "spots.emptyDesc": "Añade tu cafetería, bar o restaurante favorito arriba y los planes se construirán a su alrededor.",
    "spots.located": "localizado",
    "spots.pending": "pendiente de ubicación",
    "spots.footer": "{count} lugares guardados — alimentan tus recomendaciones de comida",
    "spots.done": "Hecho",
    "spots.addSuccess": "Añadido y localizado en el mapa.",
    "spots.addWarn": "Añadido, pero no se pudo localizar en este momento. Se volverá a intentar cuando se recomiende.",
    "spots.deleteConfirm": "¿Eliminar este lugar?",

    // Memory & Exclusions Popup (History)
    "history.title": "Memoria y Exclusiones",
    "history.subtitle": "Lo que LocalExplorer AI recuerda — y lo que nunca debe volver a sugerir",
    "history.tabMemory": "Memoria de 30 Días ({count})",
    "history.tabSkips": "Lugares Excluidos ({count})",
    "history.memoryDesc": "Para mantener tus aventuras frescas, LocalExplorer AI recuerda los lugares sugeridos y los oculta durante 30 días. Elimina lugares individuales si deseas que se sugieran antes.",
    "history.skipsDesc": "Lugares que nunca quieres que se te sugieran — en ningún plan, nunca. Añádelos con el botón de prohibición en las tarjetas, o quítalos de abajo para permitirlos de nuevo.",
    "history.noHistory": "Aún sin historial de actividad",
    "history.noHistorySub": "A medida que explores itinerarios, los lugares sugeridos se registrarán aquí.",
    "history.noSkips": "Sin exclusiones permanentes",
    "history.noSkipsSub": "Usa el botón de bloquear en cualquier actividad para excluirla de futuros planes.",
    "history.spotsTracked": "{count} lugares registrados",
    "history.resetMemory": "Reiniciar Memoria (Borrar Todo)",
    "history.skipsCount": "{count} lugares excluidos permanentemente",
    "history.clearConfirm": "¿Borrar todo el historial de 30 días? La aplicación restablecerá el filtro de repeticiones.",
    "history.today": "Hoy",
    "history.daysAgo": "hace {days}d",
    "history.excluded": "Excluido para siempre",
    "history.addedOn": "añadido el {date}",

    // Extra Activity actions
    "act.multipleChoice": "Opciones de Elección Múltiple (Clic para cambiar)",
    "act.available": "{count} Disponibles",
    "act.freshChoice": "Nueva Elección 🔄",
    "act.deleteConfirm": "¿Eliminar \"{name}\" del Día {day}?",
    "act.liveHappening": "Evento en Vivo 🔥",
    "act.activeEvent": "Evento Local Activo",
    "act.venue": "Lugar: {venue}",

  },

  eu: {
    // Navigation & Header
    "nav.brand": "LocalExplorer AI",
    "nav.subtitle": "Bidaia Kulturalen Antolatzailea eta Tokiko Gida",
    "nav.vacation": "Oporrak",
    "nav.hometown": "Herria",
    "nav.tasteProfile": "Gustu Profila",
    "nav.mySpots": "Nire Tokiak",
    "nav.history": "Historia",
    "nav.savedTrips": "Gordeak",
    "nav.syncReady": "Sinkronizatuta",
    "nav.saving": "Gordetzen...",
    "nav.offline": "Offline",
    "nav.cached": "Katxean",

    // Actions & Tools
    "action.saveTrip": "Gorde Bidaia",
    "action.saved": "Gordeta",
    "action.share": "Partekatu",
    "action.export": "Esportatu",
    "action.print": "Mapak Inprimatu",
    "action.groupHub": "Talde Gunea",
    "action.pocketGuide": "Poltsikoko Gida",
    "action.adjustSchedule": "Ordutegia Egokitu",
    "action.liveNavigator": "Zuzeneko Nabigatzailea",
    "action.regenerate": "Berreraiki Guztia",
    "action.reiterate": "Itinerarioa Hobetu",
    "action.addActivity": "Jarduera Gehitu",
    "action.allDays": "Egun Guztiak",
    "action.day": "Eguna",
    "action.days": "Egun",
    "action.close": "Itxi",
    "action.cancel": "Utzi",
    "action.save": "Gorde",
    "action.delete": "Ezabatu",
    "action.edit": "Editatu",
    "action.copyLink": "Kopiatu Gonbidapen Esteka",
    "action.copyCode": "Kopiatu Kodea",

    // Vacation Form
    "vacation.title": "Oporretako Ibilbide Antolatzailea",
    "vacation.subtitle": "Egun anitzeko ibilbide kulturalak, ezkutuko altxorrak eta ibilbide optimizatu egiaztatua",
    "vacation.tripMode": "Bidaia Modua:",
    "vacation.singleDest": "Helmuga Bakarra",
    "vacation.multiDest": "Helmuga Anitzeko Ibilbidea",
    "vacation.destinationLabel": "Helmugako Hiria edo Eskualdea (Aholkularia)",
    "vacation.geocoding": "Geolokalizazio Zehatza",
    "vacation.popular": "Ezagunak:",
    "vacation.multiCityStops": "Hiri Anitzeko Geldialdiak",
    "vacation.stop": "Geldialdia",
    "vacation.addStop": "Gehitu Beste Geldialdi / Hiri Bat",
    "vacation.groupSize": "Bidaia Taldearen Tamaina",
    "vacation.groupSizeDesc": "Zure taldean bidaiatuko duten pertsona kopurua",
    "vacation.person": "Pertsona",
    "vacation.people": "Pertsona",
    "vacation.solo": "Bakarrik Bidaiaria",
    "vacation.couple": "Bikotea (2)",
    "vacation.smallGroup": "Talde Txikia (4)",
    "vacation.largeGroup": "Talde Handia (6+)",
    "vacation.accommodationTitle": "Erreserbatutako Ostatua eta Egonaldia",
    "vacation.accommodationSubtitle": "Zehaztu hotelak, sarrera eta irteera egunak eta orduak",
    "vacation.accommodationHeading": "Erreserbatutako Ostatua eta Egonaldia",
    "vacation.accommodationSub": "Zehaztu eguneroko hasiera/amaiera puntuak, sarrera eta irteera orduak",
    "vacation.showAccommodation": "Erakutsi Ostatua",
    "vacation.hideAccommodation": "Ezkutatu Ostatua",
    "vacation.addStay": "Gehitu Beste Ostatu Bat",
    "vacation.stay": "Ostatua",
    "vacation.accommodationName": "Ostatuaren Izena",
    "vacation.accommodationPlaceholder": "adib. Maria Cristina Hotela, Alde Zaharreko Apartamentua",
    "vacation.locationAddress": "Kokapena / Helbidea / Auzoa",
    "vacation.pinOnMap": "Ainguratu Mapan",
    "vacation.searchVerify": "Bilatu kokapena egiaztatzeko",
    "vacation.geoVerified": "Geo Egiaztatua",
    "vacation.checkInDay": "Sarrera Eguna",
    "vacation.checkInHour": "Sarrera Ordua",
    "vacation.checkOutDay": "Irteera Eguna",
    "vacation.checkOutHour": "Irteera Ordua",
    "vacation.accommodationNotes": "Azalpena / Hotelaren Oharrak (Aukerakoa)",
    "vacation.accommodationNotesPlaceholder": "adib. Geltokitik 10 minutura oinez, maletak uzteko aukera",
    "vacation.remove": "Kendu",
    "vacation.arrivalHour": "Iritsiera Ordua (1. Eguna)",
    "vacation.arrivalHourDesc": "1. eguna zure iritsiera orduaren ondoren hasiko da.",
    "vacation.departureHour": "Irteera Ordua (Azken Eguna)",
    "vacation.departureHourDesc": "Azken eguna zure irteera ordua baino lehen amaituko da.",
    "vacation.transport": "Eskuragarri dauden Garraiobideak",
    "vacation.transportMulti": "Aukera Anitza",
    "vacation.transportDesc": "Hautatu bidaian zehar erabilgarri izango dituzun garraioak:",
    "vacation.transportPublic": "Garraio Publikoa eta Oinez",
    "vacation.transportPublicDesc": "Herri autobusak, trenak eta oinez",
    "vacation.transportCar": "Auto Partikularra / Alokairukoa",
    "vacation.transportCarDesc": "Ibilaldiak eta kostaldeko errepideak",
    "vacation.transportBike": "Bizikleta / Bici Elektrikoa",
    "vacation.transportBikeDesc": "Bidegorriak eta hiri ibilbideak",
    "vacation.transportTaxi": "Taxia",
    "vacation.transportTaxiDesc": "Atez ateko garraio azkarra",
    "vacation.duration": "Bidaiaren Iraupena",
    "vacation.pacing": "Esplorazio Erritmoa",
    "vacation.paceRelaxed": "Lasaia",
    "vacation.paceBalanced": "Orekatua",
    "vacation.pacePacked": "Trinkoa",
    "vacation.vibes": "Bidaiaren Giroa eta Interesak",
    "vacation.vibesDesc": "Hautatu nahi dituzun guztiak",
    "vacation.swiper": "Jarduera Aurkitzailea",
    "vacation.swiperInteractive": "Interaktiboa",
    "vacation.swiperDesc": "Arakatu eta aukeratu toki hautagaiak (argazkiak, Google Maps iritziak) azken plana sortu aurretik.",
    "vacation.budget": "Aurrekontu Modua",
    "vacation.budgetTier": "Kategoria Orokorra",
    "vacation.budgetExact": "Aurrekontu Zehatza / Eguna / Pertsona",
    "vacation.budgetSavvy": "Aurreztzailea",
    "vacation.budgetSavvyDesc": "Kaleko janaria eta bista libreak",
    "vacation.budgetMid": "Orekatua",
    "vacation.budgetMidDesc": "Jatetxe gozoak eta toki bereziak",
    "vacation.budgetLuxury": "Luxua",
    "vacation.budgetLuxuryDesc": "Michelin izarrak eta bisita gidatuak",
    "vacation.perPersonDay": "/ pertsona / eguna",
    "vacation.quickSelect": "Aukera Azkarra:",
    "vacation.estTotalBudget": "Aurreikusitako Aurrekontua Guztira:",
    "vacation.traveler": "bidaiari",
    "vacation.travelers": "bidaiari",
    "vacation.dayWord": "egun",
    "vacation.daysWord": "egun",
    "vacation.advancedNotes": "Eskaera gehigarriak edo dieta oharrak (Aukerakoa)",
    "vacation.advancedNotesPlaceholder": "adib. Pintxo begetarianoak, guraso nagusiekin bidaiatuz, arkitekturan eta surfean interesatuta...",
    "vacation.generating": "Ibilbidea Diseinatzen...",
    "vacation.submitSwiper": "Ireki Jarduera Aurkitzailea →",
    "vacation.submitMulti": "Sortu Helmuga Anitzeko Plana →",
    "vacation.submitSingle": "Sortu {days} Eguneko Ibilbidea →",

    // Vibe options
    "vibe.gastro": "Gastronomia eta Tokiko Pintxoak",
    "vibe.excursions": "Eskualdeko Ibilaldiak eta Begiratokiak",
    "vibe.shopping": "Erosketak eta Tokiko Dendak",
    "vibe.scenic": "Natura eta Aire Librekoa",
    "vibe.history": "Historia eta Arkitektura",
    "vibe.family": "Familientzat Egokia",
    "vibe.hiddenGems": "Altxor Ezkutuak / Turistarik Gabe",
    "vibe.budget": "Merkea / Ekonomikoa",
    "vibe.nightlife": "Gaueko Giroa eta Tabernak",
    "vibe.art": "Artea eta Kultura",
    "vibe.relaxation": "Erlaxazioa eta Ongizatea",

    // Hometown Form
    "hometown.title": "Herriko Tokiko Gida",
    "hometown.subtitle": "Benetako herritarren planak tranpa turistiko gabe, eguraldiari eta zure denborari egokituta.",
    "hometown.liveSearchBadge": "Zuzeneko Bilaketa: Kontzertuak, Azokak eta Kirolak",
    "hometown.locationLabel": "Gaur egungo Herria edo Auzoa",
    "hometown.verifiedTown": "Koordenatu Egiaztatuak",
    "hometown.nativeResident": "Bertako Bizilagun Modua",
    "hometown.useGps": "GPSa Erabili",
    "hometown.radius": "Esplorazio Erradioa",
    "hometown.time": "Gaurko Denbora Librea",
    "hometown.timeQuick": "Azkarra",
    "hometown.timeQuickHours": "1-2 ordu",
    "hometown.timeHalf": "Egun-erdi",
    "hometown.timeHalfHours": "3-5 ordu",
    "hometown.timeFull": "Egun Osoa",
    "hometown.timeFullHours": "Egun Osoa",
    "hometown.occasion": "Okasioa eta Giro Desiratua",
    "hometown.weather": "Uneko Eguraldia",
    "hometown.liveSensor": "Zuzeneko Sentsorea",
    "hometown.presets": "Aurreikuspenak...",
    "hometown.antiRepeat": "30 Eguneko Errepikapenaren Aurkako Memoria",
    "hometown.antiRepeatDesc": "Historiala automatikoki aztertzen du berriki bisitatutako tokiak saihesteko",
    "hometown.manage": "Kudeatu",
    "hometown.residentNotes": "Gehitu Bizilagun Xehetasunak (Txakurrak onartu, kafe berezia, bidegorria)",
    "hometown.residentNotesHide": "Ezkutatu Xehetasunak",
    "hometown.discovering": "Herriko Altxorrak Bilatzen {radius}km-tan...",
    "hometown.discoverBtn": "Arakatu Tokiko Plana {city}-(e)n",

    // Occasions
    "occ.solo": "Irakurketa eta Erlaxazioa Bakarrik",
    "occ.soloDesc": "Kafetegi lasaiak, liburu-dendak, parkeak",
    "occ.date": "Hitzordua eta Gaueko Giroa",
    "occ.dateDesc": "Bistrot erromantikoak, ilunabarrak",
    "occ.adventure": "Aire Libreko Abentura",
    "occ.adventureDesc": "Mendi bideak, begiratokiak, ibai bazterrak",
    "occ.rainy": "Egun Euritsurako Barruko Plana",
    "occ.rainyDesc": "Museoak, kafetegi goxoak, galeriak",
    "occ.tapas": "Pintxo Ibilbidea eta Tabernak",
    "occ.tapasDesc": "Pintxo barra bikainak eta herrikoiak",
    "occ.nature": "Natura eta Eremu Berdeak",
    "occ.natureDesc": "Natura santutegiak eta hezeguneak",
    "occ.vintage": "Altxor Ezkutuak eta Vintage",
    "occ.vintageDesc": "Indie biniloak, denda bereziak, lorategiak",
    "occ.family": "Familia Plana Haurrekin",
    "occ.familyDesc": "Parke interaktiboak eta askari goxoak",

    // Itinerary & Timeline
    "itinerary.budgetTier": "Aurrekontu Maila",
    "itinerary.pacing": "Erritmoa",
    "itinerary.pacing.relaxed": "Lasaia",
    "itinerary.pacing.balanced": "Orekatua",
    "itinerary.pacing.packed": "Trinkoa",
    "itinerary.totalBudget": "Aurrekontu Estimatua",
    "itinerary.transit": "Garraioa",
    "itinerary.morning": "Goiza",
    "itinerary.afternoon": "Arratsaldea",
    "itinerary.evening": "Iluntzea",
    "itinerary.night": "Gaua",
    "itinerary.mustSee": "Derrigorrezkoa",
    "itinerary.hiddenGem": "Altxor Ezkutua",
    "itinerary.culturalSignificance": "Kultur Garrantzia",
    "itinerary.localTip": "Tokiko Aholkua eta Ohiturak",
    "itinerary.weather": "Eguraldia",
    "itinerary.walk": "oinez",
    "itinerary.drive": "autoz",
    "itinerary.taxi": "taxiz",
    "itinerary.viewMap": "Ikusi Mapa eta Ibilbidea",
    "itinerary.costPerPerson": "Kostu Est. / Pertsona",
    "itinerary.free": "Doakoa",
    "itinerary.replaceActivity": "Aldatu Jarduera",
    "itinerary.deleteActivity": "Ezabatu",
    "itinerary.moveUp": "Eraman Lehenago",
    "itinerary.moveDown": "Eraman Beranduago",
    "itinerary.markVisited": "Bisitatua",
    "itinerary.markUnvisited": "Markatu Bisitatua",
    "itinerary.directions": "Nola Iritsi (Google Maps)",
    "itinerary.reviews": "Iritziak eta Aholku Egiaztatuak",

    // Group Hub Modal
    "collab.title": "Taldeko Bidaia Gunea eta Elkarlana",
    "collab.subtitle": "Kudeatu taldeko sarbidea, eguneko bozketa, maletak eta Tricount gastu partekatuak",
    "collab.activeUser": "Bidaiari Aktiboa",
    "collab.rename": "Izena Aldatu",
    "collab.addMember": "Gehitu Bidaiaria",
    "collab.tab.votes": "Eguneko Jardueren Bozketa",
    "collab.tab.packing": "Maleta eta Tresnak",
    "collab.tab.expenses": "Tricount Gastuak",
    "collab.tab.members": "Kideak eta Sarbidea",
    "collab.consensus.title": "Taldearen Adostasuna eta Bozketa Egunero",
    "collab.consensus.desc": "Bozkatu egun bakoitzeko tokiak taldeko adostasuna ixteko.",
    "collab.vote.mustDo": "Derrigorrezkoa",
    "collab.vote.soundsGood": "Ondo deritzot",
    "collab.vote.pass": "Hurrengora",
    "collab.packing.readiness": "{name}(r)en Maleta Prestakuntza",
    "collab.packing.packed": "{packed} / {total} elementu paketatuta",
    "collab.packing.add": "Gehitu elementu pertsonalizatua...",
    "collab.expenses.totalSpend": "Taldeko Gastu Guztira",
    "collab.expenses.balances": "Tricount Kideen Saldo Garbiak",
    "collab.expenses.settlementPlan": "Zorrak Kitatzeko Plan Optimua (Nork Nori)",
    "collab.expenses.addExpense": "+ Erregistratu Gastu Berria",
    "collab.members.accessMode": "Sarbide Baimenen Modua",
    "collab.members.inviteCode": "Gonbidapen Kodea",

    // Schedule Adjuster
    "schedule.title": "Zuzeneko Ordutegi Egokitzea eta Berregokitzea",
    "schedule.subtitle": "Aurreikusi baino beranduago edo lehenago zoaz? Egokitu eguna ibilbide adimendunekin",
    "schedule.runningAhead": "Aurretik Noa",
    "schedule.runningBehind": "Berandu Noa",
    "schedule.recalculate": "Ezarri Ordutegi Berria",
    "schedule.minutes": "minutu",
    "schedule.selectDay": "Aukeratu Eguna Egokitzeko:",
    "schedule.delayStart": "Noiztik aurrera hasi da aldaketa?",
    "schedule.delayStartDesc": "Aurreko jarduerak ez dira aldatuko",
    "schedule.fromStart": "Egunaren hasieratik (Jarduera guztiak)",
    "schedule.fromSpot": "#{idx}. tokitik aurrera: {time} — {name}",
    "schedule.offset": "Ordutegi Aldaketa:",
    "schedule.behind": "+{minutes} min (Berandu)",
    "schedule.ahead": "{minutes} min (Aurretik)",
    "schedule.onSchedule": "Ordutegian (0m)",
    "schedule.compress": "Ondorengo geldialdien iraupena murriztu (Berreskuratze Azkarra)",
    "schedule.compressDesc": "Automatikoki 10-15 minutu murrizten ditu ondorengo lekuetan, afaria edo ixte-ordua ez pasatzeko.",
    "schedule.constraints": "Detektatutako Ordutegi Mugak eta Oharrak:",
    "schedule.preview": "Ordutegi Berriaren Aurrebista ({day}. Eguna):",
    "schedule.allShifted": "Jarduera guztiak mugituta",
    "schedule.shiftedFrom": "#{spot}. tokitik aurrera mugituta",
    "schedule.untouched": "Aldaketarik gabe",
    "schedule.original": "Jatorrizkoa: {time}",
    "schedule.reset": "Berrezarri Jatorrizko Ordutegira",
    "schedule.applyDay": "Aplikatu {day}. Egunari",

    // Pocket Offline Guide
    "pocket.title": "Poltsikoko Offline Gida",
    "pocket.subtitle": "Bateria aurrezteko eta hegaldi modurako ikuspegi arina.",
    "pocket.downloadPdf": "Gorde Bidaiaren PDFa",
    "pocket.emergency": "Larrialdietarako Zenbakiak eta Tokiko Ohiturak",
    "pocket.airplaneReady": "Hegaldi Modurako Prest",
    "pocket.zeroInternet": "Internetik Gabe Erabiltzeko Modukoa",
    "pocket.cached": "Nabigatzailean Gordeta",
    "pocket.notCached": "Oraindik ez dago offline gordeta",
    "pocket.visitedCount": "{count}/{total} Bisitatuta ({percent}%)",
    "pocket.cacheBtn": "💾 Gorde Bidaia Offline",
    "pocket.cachedBtn": "✓ Offline Gordeta",
    "pocket.downloadHtml": "Deskargatu HTML Fitxategia",
    "pocket.tabChecklist": "📋 Zerrenda eta Ordutegia",
    "pocket.tabNotes": "📝 Offline Oharrak eta Memoriak",
    "pocket.tabEmergency": "🚨 Larrialdiak eta Informazioa",
    "pocket.showRemaining": "Egin gabekoak ikusi",
    "pocket.showAll": "Guztiak ikusi",
    "pocket.allVisited": "🎉 Egun honetako toki guztiak bisitatu dira!",
    "pocket.notesTip": "💡 Hemen idatzitako oharrak zure gailuan lokalean gordeko dira eta deskargatutako gidan agertuko dira.",
    "pocket.notesPlaceholder": "Gehitu ateetako kodeak, erreserba zenbakiak, larrialdi oharrak edo gogorarazleak...",
    "pocket.emergencyTitle": "Larrialdietarako Telefono Garrantzitsuak",
    "pocket.emergencyDesc": "Gorde edo idatzi kontaktu hauek internetik gabe ibili aurretik:",
    "pocket.emergencyEU": "Larrialdi Orokorrak (EB)",
    "pocket.medical": "Osasun Larrialdiak / Anbulantzia",
    "pocket.localPolice": "Udaltzaingoa",
    "pocket.nationalPolice": "Polizia Nazionala",
    "pocket.phrasesTitle": "Oinarrizko Tokiko Esaldiak (Gaztelania / Euskara)",
    "pocket.readyOffline": "{dest} konexiorik gabe esploratzeko prest",

    // Day Card
    "day.plannedSpots": "{count} toki planifikatuta",
    "day.mappedSpots": "{count} Toki Mapan",
    "day.estBudget": "Aurrek. {budget}",
    "day.adjustSchedule": "Ajustatu Ordutegia / Berandu bazabiltza",
    "day.exportGoogleMaps": "Esportatu Eguneko Ibilbidea Google Maps-era",
    "day.directions": "Nola heldu",
    "day.addCustomSpot": "Gehitu Toki Pertsonalizatua {day}. Egunari",
    "day.deleteConfirm": "Ezabatu {day}. Eguna?",

    // Activity Card & Details
    "act.swap": "Aldatu Tokia",
    "act.swapping": "Aldatzen...",
    "act.visited": "Bisitatua",
    "act.markVisited": "Markatu Bisitatua",
    "act.details": "Xehetasunak eta Gida",
    "act.tickets": "Sarrerak / Erreserba",
    "act.mapsReviews": "Mapa eta Iritziak",
    "act.notes": "Oharrak",
    "act.note": "Oharra",
    "act.reviews": "Iritziak",
    "act.hideReviews": "Ezkutatu Iritziak",
    "act.insiderTip": "Bertako Aholkua:",
    "act.groupNotesTitle": "Taldearen Oharrak eta Aholkuak",
    "act.noNotes": "Oraindik ez dago oharrik toki honetarako. Gehitu erreserba edo ideiak behean!",
    "act.addNotePlaceholder": "Gehitu oharra {user} bezala...",
    "act.permanentSkip": "Baztertu Tokia Betirako",
    "act.permanentSkipPrompt": "Ez gomendatu \"{name}\" inoiz gehiago?\n\nEtorkizuneko plan guztietatik betirako baztertuko da.",

    // Activity Deep Details Modal
    "detail.storyAndDetails": "Historia eta Xehetasunak",
    "detail.exactLocation": "Kokapen Zehatza eta Puntuak",
    "detail.anecdotes": "Anekdotak eta Tradizioa",
    "detail.askGuide": "Galdetu Gidariari",
    "detail.aboutExperience": "Esperientzia Honi Buruz",
    "detail.historicalContext": "Testuinguru Historikoa eta Sustraiak",
    "detail.culturalSignificance": "Kultur Garrantzia",
    "detail.visualHighlights": "Arkitektura eta Ikuspegi Nabarmenak",
    "detail.whatToExpect": "Zer Espero",
    "detail.practicalGuide": "Bisitarientzako Gida Praktikoa",
    "detail.bestTimeToVisit": "Bisitatzeko Garai Onena",
    "detail.photographyTip": "Argazki Aholkua",
    "detail.insiderSecret": "Bertako Sekretua",
    "detail.chatCtaTitle": "Leku honi buruzko galderarik baduzu?",
    "detail.chatCtaDesc": "Txateatu zuzenean zure AI Tokiko Gidariarekin: {spot}.",
    "detail.chatWithGuide": "Txateatu Gidariarekin",
    "detail.exactCoords": "Koordenatu Zehatzak eta Barne Ibilbidea",
    "detail.openMaps": "Ireki Maps-en",
    "detail.mustVisitWithin": "Eremu Honetako Ezinbestekoak ({count} Gune Giltzarri)",
    "detail.whyStopHere": "Zergatik gelditu hemen: ",
    "detail.singleLocation": "Kokapen Bakarra",
    "detail.singleLocationDesc": "Jarduera hau eraikin edo monumentu honetan kokatzen da. Mapak sarrera nagusia eta topalekua adierazten ditu.",
    "detail.anecdotesTitle": "Anekdotak, Kondairak eta Ahozko Tradizioa",
    "detail.anecdotesDesc": "Gertaera historiko liluragarriak, bitxikeriak eta {dest}(e)n belaunaldiz belaunaldi transmititutako ipuinak.",
    "detail.quote": "Aipu Ospetsua",
    "detail.guideHeader": "Tokiko Gida eta Bidaia Agentea",
    "detail.guideSub": "Aditua zuzenean {spot} eta {dest}(r)i buruz",
    "detail.guideHint": "Galdetu aipuak, historia, plater tipikoak edo istorioak",
    "detail.thinking": "Tokiko ezagutza kontsultatzen...",
    "detail.suggestedQuestions": "Gomendatutako Galderak:",
    "detail.chatPlaceholder": "Galdetu {spot}, historia, anekdotak edo aholkuei buruz...",
    "detail.ask": "Galdetu",
    "detail.aiEnabled": "Mundu mailako AI esplorazio dinamikoa gaituta",

    // Saved Trips Drawer
    "saved.title": "Gordetako Bidaiak",
    "saved.searchPlaceholder": "Bilatu helmuga edo bidaiaren izena...",
    "saved.all": "Guztiak",
    "saved.vacations": "Oporrak",
    "saved.hometown": "Herria",
    "saved.noTrips": "Ez da gordetako ibilbiderik aurkitu",
    "saved.noTripsSub": "Diseinatu bidaia bat eta sakatu \"Gorde Bidaia\" bertan gordetzeko.",
    "saved.openPlan": "Ireki Plana",

    // Categories
    "category.food": "Tokiko Taberna / Jatetxea",
    "category.nature": "Natura eta Ibilaldia",
    "category.culture": "Kultura eta Artea",
    "category.sightseeing": "Monumentua / Leku Interesgarria",
    "category.hidden-gem": "Ezkutuko Altxorra",
    "category.shopping": "Artisautza eta Erosketak",
    "category.relaxation": "Erlaxatzeko Gunea",
    "category.nightlife": "Gaueko Giroa",
    "category.cafe": "Tokiko Kafetegia",
    "category.entertainment": "Aisialdia eta Ikuskizunak",

    // Day transit and route
    "transit.walk": "{mins} min oinez",
    "transit.transit": "{mins} min garraioan",
    "transit.drive": "{mins} min autoan/taxian",
    "transit.connection": "{mins} min konexioa",
    "transit.pleasantWalk": "Ibilaldi atsegina ({dist}) auzoan zehar {dest}-(r)untz",
    "transit.instructions": "{from}-(e)tik {to}-(e)rako konexio zuzena",
    "transit.navigate": "{from}-(e)tik {to}-(e)ra nabigatu",
    "transit.walkTo": "Oinez ({dist}) {dest}-(e)ra",

    // Extra Itinerary translations
    "itinerary.highlightsTitle": "Aukeratutako Nabarmenduak eta Sinadurak",
    "itinerary.mapTitle": "Ibilbide Geografikoa eta Jardueren Mapa",
    "itinerary.pinnedLocations": "Ainguratutako Kokapenak",
    "itinerary.customizedTitle": "Zure ordutegia egokitu duzu?",
    "itinerary.customizedDesc": "Jarduerak ezabatu edo orduz aldatu badituzu, AI-ak zure hautuak gordeko ditu eta hutsuneak herriko leku berriekin beteko ditu!",
    "itinerary.autoFillEmpty": "Bete hutsuneak automatikoki",
    "itinerary.geoVerified": "✓ Geo Egiaztatua",
    "itinerary.checkIn": "Sarrera: {day}. Eguna",
    "itinerary.checkOut": "Irteera: {day}. Eguna",

    // Taste Profile Popup
    "taste.title": "Gustu Profila",
    "taste.subtitle": "Esan AI-ari nola gustatzen zaizun jatea eta edatea — gomendioak zure gustuetara eta egun bakoitzeko planera egokituko dira",
    "taste.explanation": "AI-ak profil hau erabiltzen du zure gustuko tabernak, kafetegiak eta jatetxeak aukeratzeko, eta eguneko dinamikarekin uztartzen ditu (taberna lasai bat mendi ibilaldi baten ondoren, terraza bat ilunabarreko ibilbidearen aurretik, gune goxo bat euri egun batean).",
    "taste.diningLabel": "Nola gustatzen zaizu jatea?",
    "taste.drinkLabel": "Zer gustatzen zaizu edatea?",
    "taste.atmosphereLabel": "Zein giro duzu gogoko?",
    "taste.dislikesLabel": "Zer saihestu behar da?",
    "taste.budgetLabel": "Jateko aurrekontu arrunta",
    "taste.dietaryLabel": "Dieta oharrak",
    "taste.selectAll": "Hautatu aplikatzen diren guztiak",
    "taste.avoidHint": "AI-ak guztiz saihestuko ditu hauek",
    "taste.optional": "Aukerakoa",
    "taste.clear": "Ezabatu profila",
    "taste.save": "Gorde Gustu Profila",
    "taste.saved": "Gordeta",
    "taste.placeholder": "adib. Begetarianoa, glutenik gabea, minak gogoko ditut, mariskorik ez…",
    "taste.clearConfirm": "Zure gustu profila ezabatu nahi duzu? Gomendio gastronomikoak ez dira pertsonalizatuko.",

    // Taste options details
    "taste.style.pintxo": "Pintxo ibilbideak / Tapeoa",
    "taste.style.sitdown": "Eserita jateko jatetxea",
    "taste.style.market": "Merkatuko postuak",
    "taste.style.quick": "Janari azkarra / kalekoa",
    "taste.style.tasting": "Dastatze menu luzea",
    "taste.style.picnic": "Piknika eta eramateko janaria",
    "taste.drink.coffee": "Kafetegi berezia / Kea",
    "taste.drink.wine": "Tokiko ardoa / txakolina",
    "taste.drink.beer": "Garagardo artisaua",
    "taste.drink.cocktails": "Koktelak eta konbinatuak",
    "taste.drink.cider": "Sagardoa (sagardotegi estilora)",
    "taste.drink.tea": "Te eta infusioak",
    "taste.drink.nonalcoholic": "Alkoholik gabeko aukerak",
    "taste.atmosphere.quiet": "Lasaia eta goxoa",
    "taste.atmosphere.lively": "Bizia eta soziala",
    "taste.atmosphere.terrace": "Terraza / Aire librean",
    "taste.atmosphere.historic": "Historikoa eta klasikoa",
    "taste.atmosphere.modern": "Modernoa eta dotorea",
    "taste.atmosphere.family": "Familia giroa",
    "taste.dislike.tourist": "Tranpa turistikoak",
    "taste.dislike.chains": "Kateak eta frankiziak",
    "taste.dislike.queues": "Ilar luzeak",
    "taste.dislike.loud": "Musika altua",
    "taste.dislike.crowded": "Toki jabetuak",
    "taste.budget.easy": "Merkea",
    "taste.budget.easyDesc": "Barrak, eguneko menuak",
    "taste.budget.balanced": "Orekatua",
    "taste.budget.balancedDesc": "Janari ona, prezio egokia",
    "taste.budget.luxury": "Luxuzkoa",
    "taste.budget.luxuryDesc": "Goi-mailako esperientziak",

    // My Places Popup
    "spots.title": "Nire Tokiak",
    "spots.subtitle": "Zure tabernak, kafetegiak eta jatetxeak — jatetxe gomendioetarako iturri bakarra",
    "spots.explanation": "LocalExplorer-ek ez ditu inoiz tabernak edo jatetxeak asmatzen zerrenda finko batetik. Janari gomendioak zuk hemen gehitutako tokietatik edo AI bilaketatik datoz — guztia mapan dinamikoki kokatuta.",
    "spots.category.bar": "Taberna",
    "spots.category.cafe": "Kafetegia",
    "spots.category.restaurant": "Jatetxea",
    "spots.category.other": "Beste gogoko bat",
    "spots.formName": "Lekuaren izena *",
    "spots.formType": "Mota",
    "spots.formTown": "Herria / Eremua",
    "spots.formNote": "Oharra (aukerakoa)",
    "spots.placeholderName": "adib. Bar Iruña, Kafé Bergara…",
    "spots.placeholderTown": "adib. Bilbo, Euskal Herria",
    "spots.placeholderNote": "adib. tortillarik onena ostiraletan",
    "spots.btnSaving": "Kokatzen...",
    "spots.btnAdd": "Gehitu Lekua",
    "spots.empty": "Ez dago gordetako tokirik",
    "spots.emptyDesc": "Gehitu zure kafetegi, taberna edo jatetxe gogokoena goian eta planak haren inguruan eraikiko dira.",
    "spots.located": "kokatuta",
    "spots.pending": "kokapenaren zain",
    "spots.footer": "{count} toki gorde dira — hauek elikatzen dituzte zure jatetxe gomendioak",
    "spots.done": "Egina",
    "spots.addSuccess": "Gehituta eta mapan kokatuta.",
    "spots.addWarn": "Gehituta, pero ezin izan da kokatu une honetan. Gomendatzen denean berriro saiatuko da.",
    "spots.deleteConfirm": "Leku hau ezabatu nahi duzu?",

    // Memory & Exclusions Popup (History)
    "history.title": "Memoria eta Kanporatzeak",
    "history.subtitle": "LocalExplorer AI-ak gogoratzen duena — eta inoiz gehiago gomendatu behar ez duena",
    "history.tabMemory": "30 Eguneko Memoria ({count})",
    "history.tabSkips": "Betiko Ezabatuak ({count})",
    "history.memoryDesc": "Zure abenturak fresko mantentzeko, LocalExplorer AI-ak gomendatutako tokiak gogoratzen ditu eta 30 egunez ezkutatzen ditu. Kendu banakako tokiak lehenago gomenda ditzan.",
    "history.skipsDesc": "Inoiz berriro gomendatu nahi ez dituzun tokiak — inon, inoiz ez. Gehitu zerrenda honetara debeku botoiarekin, edo kendu hemendik baimena emateko.",
    "history.noHistory": "Ez dago jarduera historialik oraindik",
    "history.noHistorySub": "Ibilbideak arakatu ahala, gomendatutako tokiak hemen erregistratuko dira.",
    "history.noSkips": "Ez dago betiko ezabatutako tokirik",
    "history.noSkipsSub": "Erabili debekatzeko botoia edozein jardueratan betirako kanporatzeko.",
    "history.spotsTracked": "{count} toki erregistratuta",
    "history.resetMemory": "Garbitu Memoria (Reset)",
    "history.skipsCount": "{count} toki betirako kanporatuta",
    "history.clearConfirm": "30 eguneko historial guztia garbitu? Repetizioen aurkako iragazkia berrabiaraziko da.",
    "history.today": "Gaur",
    "history.daysAgo": "duela {days} egun",
    "history.excluded": "Betiko kanporatua",
    "history.addedOn": "{date}-(e)n gehituta",

    // Extra Activity actions
    "act.multipleChoice": "Aukera Anitzeko Alternatibak (Klikatu aldatzeko)",
    "act.available": "{count} Eskuragarri",
    "act.freshChoice": "Aukera Berria 🔄",
    "act.deleteConfirm": "Ezabatu \"{name}\" {day}. Egunetik?",
    "act.liveHappening": "Zuzeneko Giroa 🔥",
    "act.activeEvent": "Herriko Ekitaldia",
    "act.venue": "Lekua: {venue}",

  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language;
      if (saved && (saved === "en" || saved === "es" || saved === "eu")) {
        return saved;
      }
    } catch {
      // ignore
    }
    return "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    } catch {
      // ignore
    }
  };

  const t = (key: string, fallbackOrParams?: string | Record<string, string | number>): string => {
    let raw = translations[language]?.[key] || translations["en"]?.[key];

    if (!raw) {
      if (typeof fallbackOrParams === "string") return fallbackOrParams;
      return key;
    }

    if (typeof fallbackOrParams === "object" && fallbackOrParams !== null) {
      Object.entries(fallbackOrParams).forEach(([paramKey, paramVal]) => {
        raw = raw.replace(new RegExp(`\\{${paramKey}\\}`, "g"), String(paramVal));
      });
    }

    return raw;
  };

  const formatCurrency = (amount: number, currencySymbol = "€"): string => {
    const formatted = amount.toFixed(2);
    if (language === "eu" || language === "es") {
      return `${formatted.replace(".", ",")} ${currencySymbol}`;
    }
    return `${currencySymbol}${formatted}`;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatCurrency }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
